= resilience4j-spring-boot4

This add-on gives simple to use and highly configurable Spring Boot 4 starter.
With this starter you can apply rate limiters and circuit breakers to any of your beans by using annotations and configuration files.

NOTE: For detailed documentation look at our *https://resilience4j.readme.io/docs/getting-started-3[Usage Guide]*

[NOTE]
====
**Aspect Order**

The default aspect order is:

`Retry ( CircuitBreaker ( RateLimiter ( TimeLimiter ( Bulkhead ( Function ) ) ) ) )`

This means `Retry` is applied last. Each retry attempt is individually recorded by the `CircuitBreaker`, which allows the circuit to open quickly when a downstream system is unavailable.

You can customize the order using the following properties:

[source,properties]
----
resilience4j.retry.retryAspectOrder
resilience4j.circuitbreaker.circuitBreakerAspectOrder
resilience4j.ratelimiter.rateLimiterAspectOrder
resilience4j.timelimiter.timeLimiterAspectOrder
resilience4j.bulkhead.bulkheadAspectOrder
----

For more details, see the https://resilience4j.readme.io/docs/getting-started-3[Getting Started guide].
====

== License

Copyright 2025 Robert Winkler and Bohdan Storozhuk, Artur Havliukovskyi

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
