= CircuitBreaker for Java8
:author: Robert Winkler
:version: 0.1.4
:hardbreaks:

image:https://travis-ci.org/RobWin/circuitbreaker-java8.svg?branch=master["Build Status", link="https://travis-ci.org/RobWin/circuitbreaker-java8"] image:https://coveralls.io/repos/RobWin/circuitbreaker-java8/badge.svg["Coverage Status", link="https://coveralls.io/r/RobWin/circuitbreaker-java8"] image:https://api.bintray.com/packages/robwin/maven/circuitbreaker-java8/images/download.svg[link="https://bintray.com/robwin/maven/circuitbreaker-java8/_latestVersion"] image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]

This library is an easy-to-use implementation of the http://martinfowler.com/bliki/CircuitBreaker.html[CircuitBreaker pattern] optimized for Java 8 and functional programming in a multithreaded environment.
The library provides several higher-order functions to decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` with a Circuit Breaker. In the following I call the higher-order functions `decorators`. The decorators return an enhanced version of your function. Furthermore, the library provides decorators to measure runtime metrics of your functions by using https://dropwizard.github.io/metrics/[Dropwizard Metrics] and decorators to retry a failed function. You can stack more than one decorator on any given function. That means, you can combine a Metrics decorator with a CircuitBreaker decorator. Any decorated function can be invoked synchronously or asynchronously.
The project should be combined with a functional library for Java 8 like https://github.com/javaslang/javaslang[javaslang]. The project requires at least JDK 8.

The CircuitBreaker is implemented via a finite state machine with three states: `CLOSED`, `OPEN` and `HALF_OPEN`. The CircuitBreaker does not know anything about the backend's state by itself, but uses the information provided by the decorators via `CircuitBreaker::recordSuccess()` and `CircuitBreaker::recordFailure(throwable)`. The decorators are pure functions. The result of a decorator depends solely on the input parameters. See example: 

[source,java]
----
static <T> Supplier<T> decorateSupplier(Supplier<T> supplier, CircuitBreaker circuitBreaker){
    return () -> {
        circuitBreaker.isCallPermitted();
        try {
            T returnValue = supplier.get();
            circuitBreaker.recordSuccess();
            return returnValue;
        } catch (Exception exception) {
            circuitBreaker.recordFailure(exception);
            throw exception;
        }
    };
}
----

The state of the CircuitBreaker changes from `CLOSED` to `OPEN` if a (configurable) number of call attempts have failed consecutively. Then, all access to the backend is blocked for a (configurable) time interval. `CircuitBreaker::isCallPermitted()` throws a `CircuitBreakerOpenException`, if the CircuitBreaker is `OPEN`.
After the time interval has elapsed, the CircuitBreaker state changes to `HALF_CLOSED` and allows calls to see if the backend is still unavailable or has become available again. On success or failure, the state changes back to `CLOSED` or `OPEN`, respectively. `CircuitBreaker::recordFailure(exception)` also checks if the type of exception should increase the number of failure attempts.

== Usage guide

=== Adding circuitbreaker-java8 to your project
The project is published in JCenter and Maven Central.

==== Gradle
[source,groovy]
[subs="attributes"]
----
repositories {
    jcenter()
}

compile "io.github.robwin:circuitbreaker-java8:{version}"
----

=== CircuitBreaker configuration example

This library comes with an `InMemoryCircuitBreakerRegistry` based on a `ConcurrentMap` which provides thread safety and atomicity guarantees. You must use the CircuitBreakerRegistry to manage (create and retrieve) your CircuitBreakers. You can create a `InMemoryCircuitBreakerRegistry` with a default global `CircuitBreakerConfig` for all of your CircuitBreakers.

[source,java]
----
// Create a InMemoryCircuitBreakerRegistry with a default global configuration
// (maxFailures = 3, waitInterval = 60[s], ignoredExceptions = empty)
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
----

As an alternative you can provide your own custom global `CircuitBreakerConfig`. In order to create a custom global CircuitBreakerConfig or a CircuitBreakerConfig for a specific CircuitBreaker, you can use the CircuitBreakerConfig builder. You can configure the maximum number of allowed failures and the wait interval [ms], which specifies how long the CircuitBreaker should stay in state `OPEN`. Furthermore, you can add exceptions to the ignore list which must not trigger the CircuitBreaker.

[source,java]
----
// Create a custom configuration for a CircuitBreaker
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
    .maxFailures(1)
    .waitInterval(1000)
    .ignoredException(BusinessException.class)
    .ignoredException(AnotherBusinessException.class)
    .build();
    
// Create a InMemoryCircuitBreakerRegistry with a custom global configuration
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);

// Get a CircuitBreaker from the CircuitBreakerRegistry with the global default configuration
CircuitBreaker circuitBreaker2 = circuitBreakerRegistry.circuitBreaker("otherName");

// Get a CircuitBreaker from the CircuitBreakerRegistry with a custom configuration
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);
----

=== Functional programming example

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `CircuitBreaker.decorateCheckedSupplier()`, `CircuitBreaker.decorateCheckedRunnable()` or `CircuitBreaker.decorateCheckedFunction()`. You can invoke the returned function with `Try.of()` or `Try.run()` from https://github.com/javaslang/javaslang[javaslang]. This allows to chain further functions with `map`, `flatMap`, `filter`, `recover` or `andThen`. The chained functions are only invoked, if the CircuitBreaker is CLOSED or HALF_CLOSED. 
In the following example, `Try.of()` returns a `Success<String>` Monad, if the invocation of the function is successful. If the function throws an exception, a `Failure<Throwable>` Monad is returned and `map` is not invoked.

[source,java]
----
// Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName");

// When
Try.CheckedSupplier<String> decoratedSupplier = CircuitBreaker
        .decorateCheckedSupplier(() -> "This can be any method which returns: 'Hello", circuitBreaker);

// You can chain other functions with `map` and `flatMap`.
// The `Try` Monad returns a `Success<String>`, if all functions run successfully.
Try<String> result = Try.of(decoratedSupplier)
                .map(value -> value + " world'");

// Then
assertThat(result.isSuccess()).isTrue();
assertThat(result.get()).isEqualTo("This can be any method which returns: 'Hello world'");
----

You could also chain functions which are decorated by different CircuitBreakers.

[source,java]
----
//Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");
CircuitBreaker anotherCircuitBreaker = circuitBreakerRegistry.circuitBreaker("anotherTestName");

// When I create a Supplier and a Function which are decorated by different CircuitBreakers
Try.CheckedSupplier<String> decoratedSupplier = CircuitBreaker
        .decorateCheckedSupplier(() -> "Hello", circuitBreaker);

Try.CheckedFunction<String, String> decoratedFunction = CircuitBreaker
        .decorateCheckedFunction((input) -> input + " world", anotherCircuitBreaker);

// and I chain a function with `map`.
Try<String> result = Try.of(decoratedSupplier)
        .map(decoratedFunction);

// Then
assertThat(result.get()).isEqualTo("Hello world");
----

=== OPEN CircuitBreaker example

In this test case `map` is not invoked, because the CircuitBreaker is OPEN. The call to `Try.of` returns a `Failure<Throwable>` Monad so that the chained function is not invoked.

[source,java]
----
// Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
// Create a custom configration so that only 1 failure is allowed and the wait interval is 1[s]
CircuitBreakerConfig circuitBreakerConfig = new CircuitBreakerConfig.Builder()
    .maxFailures(1)
    .waitInterval(1000)
    .build();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);

// CircuitBreaker is initially CLOSED
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED); 
// Simulate a failure attempt
circuitBreaker.recordFailure(new RuntimeException());
// CircuitBreaker is still CLOSED, because 1 failure is allowed
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED); 
// Simulate a failure attempt
circuitBreaker.recordFailure(new RuntimeException());
// CircuitBreaker is OPEN, because maxFailures > 1
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.OPEN); 

// When I decorate my function and invoke the decorated function
Try<String> result = Try.of(CircuitBreaker.decorateCheckedSupplier(() -> "Hello", circuitBreaker))
        .map(value -> value + " world");

// Then the call fails, because CircuitBreaker is OPEN
assertThat(result.isFailure()).isTrue();
// and the exception is a CircuitBreakerOpenException
assertThat(result.failed().get()).isInstanceOf(CircuitBreakerOpenException.class); 
----

=== Recovery example

If you want to recover from any exception, you can chain the method `Try.recover()`. The recovery method is only invoked, if `Try.of()` returns a `Failure<Throwable>` Monad.

[source,java]
----
//Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName");

// When I decorate my function and invoke the decorated function
Try.CheckedSupplier<String> checkedSupplier = CircuitBreaker.decorateCheckedSupplier(() -> {
        Thread.sleep(1000);
        throw new RuntimeException("BAM!");
    }, circuitBreaker);
Try<String> result = Try.of(checkedSupplier)
        .recover((throwable) -> "Hello Recovery");

//Then the function should be a success, because the exception could be recovered
assertThat(result.isSuccess()).isTrue();
// and the result must match the result of the recovery function.
assertThat(result.get()).isEqualTo("Hello Recovery");
----

=== Ignore exceptions example

The following test cases shows how to add exceptions to the ignore list which must not trigger the CircuitBreaker.

[source,java]
----
// Given I add the IOException to the ignore list
CircuitBreakerConfig circuitBreakerConfig = new CircuitBreakerConfig.Builder()
        .maxFailures(1)
        .waitInterval(1000)
        .ignoredException(IOException.class)
        .build();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName", circuitBreakerConfig);

// Simulate a failure attempt
circuitBreaker.recordFailure(new RuntimeException());
// CircuitBreaker is still CLOSED, because 1 failure is allowed
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED);

//When the functions throws a subclass of IOException
Try.CheckedRunnable checkedRunnable = CircuitBreaker.decorateCheckedRunnable(() -> {
    throw new SocketTimeoutException("BAM!");
}, circuitBreaker);
Try result = Try.run(checkedRunnable);

//Then the SocketTimeoutException did not trigger the CircuitBreaker, but is rethrown instead.
assertThat(result.isFailure()).isTrue();
// and the CircuitBreaker is still CLOSED, because SocketTimeoutException was ignored
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED);
// and the returned exception is of type IOException
assertThat(result.failed().get()).isInstanceOf(IOException.class);
----

=== Retry example

You can also retry a failed function.

[source,java]
----
// Given I have a HelloWorldService which throws an exception
HelloWorldService  helloWorldService = mock(HelloWorldService.class);
given(helloWorldService.sayHelloWorld()).willThrow(new WebServiceException("BAM!"));

// Create a Retry with default configuration
// (maxAttempts = 3, waitInterval = 500[ms], ignoredExceptions = empty)
Retry retryContext = Retry.ofDefaults();
// Decorate the invocation of the HelloWorldService
Try.CheckedSupplier<String> retryableSupplier = Retry.retryableCheckedSupplier(helloWorldService::sayHelloWorld, retryContext);

// When I invoke the function
Try<String> result = Try.of(retryableSupplier).recover((throwable) -> "Hello world from recovery function");

// Then the helloWorldService should be invoked 3 times
BDDMockito.then(helloWorldService).should(times(3)).sayHelloWorld();
// and the exception should be handled by the recovery function
assertThat(result.get()).isEqualTo("Hello world from recovery function");
----

As an alternative you can create a custom `RetryContext`. In order to create a custom RetryContext, you can use the RetryContext builder. You can configure the maximum number of retry attempts and the wait interval [ms] between successive attempts. Furthermore, you can add exceptions to the ignore list which must not trigger a retry.

[source,java]
----
Retry retryContext = Retry.custom().maxAttempts(2).ignoredException(WebServiceException.class).build();
----

=== CompletableFuture example

You can also invoke a decorated function asynchronously and chain further functions.

[source,java]
----
// Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");

// When
Supplier<String> decoratedSupplier = CircuitBreaker
        .decorateSupplier(() -> "This can be any method which returns: 'Hello", circuitBreaker);

CompletableFuture<String> future = CompletableFuture.supplyAsync(decoratedSupplier)
        .thenApply(value -> value + " world'");

//Then
assertThat(future.get()).isEqualTo("This can be any method which returns: 'Hello world'");
----

=== Example with Dropwizard Metrics

You can use https://dropwizard.github.io/metrics/[Dropwizard Metrics] to get runtime metrics of your functions. The project provides several higher-order functions to decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction`. The decorator creates a histogram and a meter for your function.  A histogram measures min, mean, max, standard deviation and quantiles like the median or 95th percentile of the execution time. A meter measures the rate of executions.


[source,java]
----
// Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName");
MetricRegistry metricRegistry = new MetricRegistry();
Timer timer = metricRegistry.timer(name("test"));

// When I create a long running supplier which takes 2 seconds
Try.CheckedSupplier<String> supplier = () -> {
    Thread.sleep(2000);
    return "Hello world";
};

// and decorate the supplier with a Metrics timer
Try.CheckedSupplier<String> timedSupplier = Metrics.timedCheckedSupplier(supplier, timer);

// and decorate the supplier with a CircuitBreaker
Try.CheckedSupplier<String> circuitBreakerAndTimedSupplier = CircuitBreaker
        .decorateCheckedSupplier(timedSupplier, circuitBreaker);

String value = circuitBreakerAndTimedSupplier.get();

// Then the Metrics execution counter should be 1
assertThat(timer.getCount()).isEqualTo(1);
// and the mean time should be greater than 2[s]
assertThat(timer.getSnapshot().getMean()).isGreaterThan(2);

assertThat(value).isEqualTo("Hello world");
----

== Monitoring & Reporting

You could monitor and report the state of your CircuitBreakers and runtime metrics by using Metrics https://dropwizard.github.io/metrics/3.1.0/getting-started/#health-checks[Health Checks] and https://dropwizard.github.io/metrics/3.1.0/getting-started/#reporting-via-http[Reporting via JMX or HTTP].

For example:
First, create a new HealthCheckRegistry instance:

[source,java]
----
HealthCheckRegistry healthCheckRegistry = new HealthCheckRegistry();
----

[source,java]
----
public class CircuitBreakerHealthCheck extends HealthCheck {

    private final CircuitBreakerRegistry circuitBreakerRegistry;

    public CircuitBreakerHealthCheck(CircuitBreakerRegistry circuitBreakerRegistry) {
        this.circuitBreakerRegistry = circuitBreakerRegistry;
    }

    @Override
    public HealthCheck.Result check() throws Exception {
        CircuitBreaker.State state = circuitBreakerRegistry.circuitBreaker("circuitBreakerName").getState();
        switch(state){
            case CLOSED: return HealthCheck.Result.healthy();
            case HALF_CLOSED: return HealthCheck.Result.healthy();
            default: return HealthCheck.Result.unhealthy(String.format("CircuitBreaker '%s' is OPEN.", "testName"));
        }
    }
}
----

Then register an instance of the `CircuitBreakerHealthCheck` with Metrics:

[source,java]
----
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
healthCheckRegistry.register("circuitBreakerName", new CircuitBreakerHealthCheck(circuitBreakerRegistry));
----

To report runtime metrics via JMX:

[source,java]
----
MetricRegistry metricRegistry = new MetricRegistry();
final JmxReporter reporter = JmxReporter.forRegistry(metricRegistry).build();
reporter.start();
----

== License

Copyright 2015 Robert Winkler

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
