= CircuitBreaker for Java8
:author: Robert Winkler
:version: 0.1.0
:hardbreaks:

image:https://travis-ci.org/RobWin/circuitbreaker-java8.svg?branch=master["Build Status", link="https://travis-ci.org/RobWin/circuitbreaker-java8"] image:https://coveralls.io/repos/RobWin/circuitbreaker-java8/badge.svg["Coverage Status", link="https://coveralls.io/r/RobWin/circuitbreaker-java8"] image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]

This project is an implementation of the http://martinfowler.com/bliki/CircuitBreaker.html[CircuitBreaker pattern] for Java 8 and functional programming. The project should be combined with a functional library for Java 8 like https://github.com/javaslang/javaslang[javaslang]. The project requires at least JDK 8.

This CircuitBreaker is implemented via a (timed) state machine. The CircuitBreaker does not know anything about the backend's state by itself, but uses only the information provided by calls to `CircuitBreaker::recordSuccess()` and `CircuitBreaker::recordFailure()`.
The state changes from CLOSED to OPEN after a configurable number of attempts have failed consecutively. Then, all access to the backend is blocked for a configurable time interval. After that, the CircuitBreaker is HALF_CLOSED tentatively, to see if the backend is still dead or has become available again. On success or failure, the state changes back to CLOSED or OPEN, respectively.

== Usage guide

=== CircuitBreaker configuration example

[source,java]
----
// Create a InMemoryCircuitBreakerRegistry
CircuitBreakerRegistry circuitBreakerRegistry = new InMemoryCircuitBreakerRegistry();

// Configure CircuitBreaker
// First parameter configures the maximum number of failures allowed
// Second parameter configures the wait interval [ms] and specifies how long the CircuitBreaker should stay OPEN
CircuitBreakerConfig circuitBreakerConfig = new CircuitBreakerConfig(1, 1000);

// Get a CircuitBreaker from the CircuitBreakerRegistry
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);
----

=== Functional programming style

You must wrap your `Supplier` or `Runnable` function with `CircuitBreaker.CheckedSupplier.of()` or `CircuitBreaker.CheckedRunnable.of()`. You can invoke the returned function with `Try.of()` or `Try.run()` from https://github.com/javaslang/javaslang[javaslang].
The `map` function is only invoked, if the CircuitBreaker is CLOSED or HALF_CLOSED. The call to `Try.of` returns a `Success` Monad, if the function itself does not throw an exception.

[source,java]
----
// Given
// Create a InMemoryCircuitBreakerRegistry
CircuitBreakerRegistry circuitBreakerRegistry = new InMemoryCircuitBreakerRegistry();

// Get a CircuitBreaker from the CircuitBreakerRegistry with default configuration
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName");

//When
Try<String> result = Try.of(CircuitBreaker.CheckedSupplier.of(() -> "Hello", circuitBreaker))
        .map(value -> value + " world");

//Then
assertThat(result.isSuccess()).isTrue();
assertThat(result.get()).isEqualTo("Hello world");
----

=== Example with OPEN CircuitBreaker

The `map` function is not invoked, because the CircuitBreaker is OPEN. The call to `Try.of` returns a `Failure` Monad.

[source,java]
----
// Create a InMemoryCircuitBreakerRegistry
CircuitBreakerRegistry circuitBreakerRegistry = new InMemoryCircuitBreakerRegistry();

// Configure CircuitBreaker
// First parameter configures the maximum number of failures allowed
// Second parameter configures the wait interval [ms] and specifies how long the CircuitBreaker should stay OPEN
CircuitBreakerConfig circuitBreakerConfig = new CircuitBreakerConfig(1, 1000);

// Get a CircuitBreaker from the CircuitBreakerRegistry
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);

// Prepare test case
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED); // CircuitBreaker is initially CLOSED
circuitBreaker.recordFailure();
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED); // CircuitBreaker is still CLOSED, because 1 failure is allowed
circuitBreaker.recordFailure();
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.OPEN); // CircuitBreaker is OPEN, because maxFailures > 1

// When
// Wrap a standard Java8 Supplier with a CircuitBreaker
Try<String> result = Try.of(CircuitBreaker.CheckedSupplier.of(() -> "Hello", circuitBreaker))
        .map(value -> value + " world");

// Then
assertThat(result.isFailure()).isTrue(); // Call fails, because CircuitBreaker is OPEN
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.OPEN); // CircuitBreaker is OPEN, because maxFailures > 1
assertThat(result.failed().get()).isInstanceOf(CircuitBreakerOpenException.class); // Exception was CircuitBreakerOpenException
----

=== Example of Recovery

If you want to recover from an exception, you can chain the method `Try.recover()`. The recovery method is only invoked, if `Try.of()` returns a `Failure` Monad.

[source,java]
----
//Given
CircuitBreakerRegistry circuitBreakerRegistry = new InMemoryCircuitBreakerRegistry();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName");

//When
CircuitBreaker.CheckedSupplier<String> checkedSupplier = CircuitBreaker.CheckedSupplier.of(() -> {
    throw new RuntimeException("BAM!");
}, circuitBreaker);
Try<String> result = Try.of(checkedSupplier)
        .recover((throwable) -> "Hello Recovery");

//Then
assertThat(result.isSuccess()).isTrue();
assertThat(result.get()).isEqualTo("Hello Recovery");
----

=== Example with CompletableFuture

[source,java]
----
// Given
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");

//When
CircuitBreaker.CheckedSupplier<String> checkedSupplier = CircuitBreaker.CheckedSupplier.of(() -> {
    Thread.sleep(1000);
    throw new RuntimeException("BAM!");
}, circuitBreaker);
CompletableFuture<Try<String>> future = CompletableFuture.supplyAsync(() -> Try.of(checkedSupplier)
        .recover((throwable) -> "Hello Recovery"));

//Then
Try<String> result = future.get();
assertThat(result.isSuccess()).isTrue();
assertThat(circuitBreaker.isClosed()).isTrue();
assertThat(result.get()).isEqualTo("Hello Recovery");
----

== License

Copyright 2015 Robert Winkler

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
