=== Bulkhead

==== Introduction
Provides an implementation of a bulkhead pattern that can be used to limit the amount of parallel executions - in case of backend calls to downstream dependencies, the bulkhead provides dependency isolation and load shedding. For cpu-bound work, the bulkhead provides load shedding only.

This bulkhead abstraction should work well across a variety of threading and io models. It is based on a semaphore, and unlike Hystrix, does not provide "shadow" thread pool option. It is up to the client to ensure correct thread pool sizing that will be consistent with bulkhead configuration.

==== Set-Up

Just like the CircuitBreaker, this module provides in-memory 'BulkheadRegistry'. You can use the registry to manage (create and retrieve) Bulkhead instances.

[source,java,indent=0]
----
BulkheadRegistry bulkheadRegistry = BulkheadRegistry.ofDefaults();
----

As an alternative you can provide custom global `BulkheadConfig`. In order to create a custom global BulkheadConfig or a BulkheadConfig for a specific Bulkhead, you can use the BulkheadConfig builder. You can use the builder to configure:

* max amount of parallel executions allowed by the bulkhead
* max amount of time a thread can be blocked for when attempting to enter a saturated bulkhead

[source,java,indent=0]
----
// Create a custom configuration for a Bulkhead
BulkheadConfig config = BulkheadConfig.custom()
                                      .maxConcurrentCalls(150)
                                      .maxWaitTime(100)
                                      .build();

// Create a BulkheadRegistry with a custom global configuration
BulkheadRegistry registry = BulkheadRegistry.of(config);

// Get-Or-Create a Bulkhead from the registry - bulkhead will be backed by the default config
Bulkhead bulkhead1 = registry.bulkhead("foo");

// Get-Or-Create a Bulkhead from the registry, use a custom configuration when creating the bulkhead
BulkheadConfig custom = BulkheadConfig.custom()
                                      .maxWaitTime(0)
                                      .build();

Bulkhead bulkhead2 = registry.bulkhead("bar", custom);
----

If you don't want to use the BulkheadRegistry to manage Bulkhead instances, you can also create instances directly:

[source,java,indent=0]
----
Bulkhead bulkhead1 = Bulkhead.ofDefaults("foo");

Bulkhead bulkhead2 = Bulkhead.of(
                         "bar",
                         BulkheadConfig.custom()
                                       .maxConcurrentCalls(50)
                                       .build()
                     );
----

==== Examples

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `Bulkhead.decorateCheckedSupplier()`, `Bulkhead.decorateCheckedRunnable()` or `Bulkhead.decorateCheckedFunction()`.
You can invoke the decorated function with `Try.of(...)` or `Try.run(...)` from https://github.com/javaslang/javaslang[Javaslang]. This allows to chain further functions with `map`, `flatMap`, `filter`, `recover` or `andThen`. The chained functions are only invoked, if the Bulkhead is not saturated. In the following example, `Try.of(...)` returns a `Success<String>` Monad, if the invocation of the function is successful. If the function throws an exception, a `Failure<Throwable>` Monad is returned and `map` is not invoked.

[source,java,indent=0]
----
include::../../../../../resilience4j-bulkhead/src/test/java/io/github/resilience4j/bulkhead/BulkheadTest.java[tags=shouldInvokeMap]
----

You can also chain up functions which are decorated by different Bulkheads and/or CircuitBreakers.

[source,java,indent=0]
----
include::../../../../../resilience4j-bulkhead/src/test/java/io/github/resilience4j/bulkhead/BulkheadTest.java[tags=shouldChainDecoratedFunctions]
----

==== Dynamic bulkhead reconfiguration

You can use `changeConfig` method to modify bulkhead params in runtime.
NOTE! New `maxWaitTime` duration won't affect threads that are currently waiting for permission.

===== Bulkhead and RxJava

The following example shows how to decorate an Observable by using the custom RxJava operator.

[source,java]
----
Bulkhead bulkhead = Bulkhead.ofDefaults("backendName");
Observable.fromCallable(backendService::doSomething)
          .compose(BulkheadOperator.of(bulkhead));
----

Other reactive types (Flowable, Single, Maybe and Completable) are also supported.

===== Bulkhead and Reactor

The following example shows how to decorate a Mono by using the custom Reactor operator.

[source,java]
----
Bulkhead bulkhead = Bulkhead.ofDefaults("backendName");
Mono.fromCallable(backendService::doSomething)
          .compose(BulkheadOperator.of(bulkhead));
----

Flux is also supported.

===== Saturated Bulkhead example

In this example the decorated runnable is not executed because the Bulkhead is saturated and will not allow any more parallel executions. The call to `Try.run` returns a `Failure<Throwable>` Monad so that the chained function is not invoked.

[source,java,indent=0]
----
include::../../../../../resilience4j-bulkhead/src/test/java/io/github/resilience4j/bulkhead/BulkheadTest.java[tags=bulkheadFullException]
----

===== Consume emitted BulkheadEvents

The BulkHead emits a stream of BulkHeadEvents. There are two types of events emitted: permitted execution, rejected execution & finished execution. If you want to consume these events, you have to register an event consumer.

[source,java]
----
bulkhead.getEventPublisher()
    .onCallPermitted(event -> logger.info(...))
    .onCallRejected(event -> logger.info(...))
    .onCallFinished(event -> logger.info(...));
----

==== Monitoring

The Bulkhead provides an interface to monitor the current metrics.

[source,java]
----
Bulkhead.Metrics metrics = bulkhead.getMetrics();
// Returns the number of parallel executions this bulkhead can support at this point in time.
in remainingBulkheadDepth = metrics.getAvailableConcurrentCalls()
----

===== Thread interruption

You can interrupt threads that are blocked or waiting inside bulkhead.
Our implementation doesn't throw `InterruptedException`, but set `Thread.isInterrupted` status into true,
 so you are responsible for handling this state in your client code.
In the case where we should interrupt the positive flow of code after `Thread.interrupt'ion
 we throw `BulkheadFullException` with corresponding message to preserve backward compatibility with version 1.0.0 of
 Resilience4j.