=== CircuitBreaker

==== Introduction

Resilience4j comes with an in-memory `CircuitBreakerRegistry` based on a `ConcurrentHashMap` which provides thread safety and atomicity guarantees. You can use the CircuitBreakerRegistry to manage (create and retrieve) CircuitBreaker instances. You can create a CircuitBreakerRegistry with a default global `CircuitBreakerConfig` for all of your CircuitBreaker instances as follows.

==== Set-Up
[source,java,indent=0]
----
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
----

As an alternative you can provide your own custom global `CircuitBreakerConfig`. In order to create a custom global CircuitBreakerConfig or a CircuitBreakerConfig for a specific CircuitBreaker, you can use the CircuitBreakerConfig builder. You can configure:

* the failure rate threshold in percentage above which the CircuitBreaker should trip open and start short-circuiting calls
* the wait duration which specifies how long the CircuitBreaker should stay open, before it switches to half open
* the size of the ring buffer when the CircuitBreaker is half open
* the size of the ring buffer when the CircuitBreaker is closed
* a custom CircuitBreakerEventListener which handles CircuitBreaker events
* a custom Predicate which evaluates if an exception should be recorded as a failure and thus increase the failure rate
* a list of exceptions which should increase failure count
* a list of exceptions which should be ignored and not increase failure count

[source,java,indent=0]
----
// Create a custom configuration for a CircuitBreaker
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
    .failureRateThreshold(50)
    .waitDurationInOpenState(Duration.ofMillis(1000))
    .ringBufferSizeInHalfOpenState(2)
    .ringBufferSizeInClosedState(2)
    .recordExceptions(IOException.class, TimeoutException.class)
    .ignoreExceptions(BusinessException.class, OtherBusinessException.class)
    .build();

// Create a CircuitBreakerRegistry with a custom global configuration
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);

// Get a CircuitBreaker from the CircuitBreakerRegistry with the global default configuration
CircuitBreaker circuitBreaker2 = circuitBreakerRegistry.circuitBreaker("otherName");

// Get a CircuitBreaker from the CircuitBreakerRegistry with a custom configuration
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);
----

You can register event consumer on a CircuitBreakerRegistry and take actions whenever a CircuitBreaker is created, replaced or deleted.
For example, you can register a global event consumer to every newly created CircuitBreaker as follows:

----
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
    circuitBreakerRegistry.getEventPublisher()
        .onEntryAdded(entryAddedEvent -> {
            CircuitBreaker addedCircuitBreaker =  entryAddedEvent.getAddedEntry();
            LOG.info("CircuitBreaker {} added", addedCircuitBreaker.getName());
            addedCircuitBreaker.getEventPublisher().onEvent(circuitBreakerEvent -> LOG.info(circuitBreakerEvent.toString()));
        })
        .onEntryRemoved(entryRemovedEvent -> {
            CircuitBreaker removedCircuitBreaker =  entryRemovedEvent.getRemovedEntry();
            LOG.info("CircuitBreaker {} removed", removedCircuitBreaker.getName());
        });
----

If you don't want to use the CircuitBreakerRegistry to manage CircuitBreaker instances, you can also create instances directly:

[source,java,indent=0]
----
CircuitBreaker defaultCircuitBreaker = CircuitBreaker.ofDefaults("testName");

CircuitBreaker customCircuitBreaker = CircuitBreaker.of("testName", circuitBreakerConfig);
----

==== Examples

You can decorate any `Supplier / Runnable / Function` or `CheckedRunnable / CheckedFunction` function with `CircuitBreaker.decorateCheckedSupplier()`, `CircuitBreaker.decorateCheckedRunnable()` or `CircuitBreaker.decorateCheckedFunction()`.
You can invoke the decorated function with `Try.of(...)` or `Try.run(...)` from http://www.vavr.io/[Vavr]. This allows to chain further functions with `map`, `flatMap`, `filter`, `recover` or `andThen`. The chained functions are only invoked, if the CircuitBreaker is CLOSED or HALF_OPEN.
In the following example, `Try.of(...)` returns a `Success<String>` Monad, if the invocation of the function is successful. If the function throws an exception, a `Failure<Throwable>` Monad is returned and `map` is not invoked.

[source,java,indent=0]
----
include::../../../../../resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeMap]
----

You can also chain up functions which are decorated by different CircuitBreakers.

[source,java,indent=0]
----
include::../../../../../resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java[tags=shouldChainDecoratedFunctions]
----

===== CircuitBreaker and RxJava

The following example shows how to decorate an Observable by using the custom RxJava operator.

[source,java]
----
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("backendName");
Observable.fromCallable(backendService::doSomething)
    .compose(CircuitBreakerOperator.of(circuitBreaker))
----

Other reactive types (Flowable, Single, Maybe and Completable) are also supported.

===== CircuitBreaker and Reactor

The following example shows how to decorate a Mono by using the custom Reactor operator.

[source,java]
----
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("backendName");
Mono.fromCallable(backendService::doSomething)
    .compose(CircuitBreakerOperator.of(circuitBreaker))
----

Flux is also supported.

===== OPEN CircuitBreaker example

In this example `map` is not invoked, because the CircuitBreaker is OPEN. The call to `Try.of` returns a `Failure<Throwable>` Monad so that the chained function is not invoked.

[source,java,indent=0]
----
include::../../../../../resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java[tags=shouldThrowCircuitBreakerOpenException]
----

===== Reset

The CircuitBreaker supports resetting, returning to its original state while losing all the current metrics.

[source,java]
----
circuitBreaker.reset();
----

===== Recover from an exception before call

If you want to recover from an exception before the CircuitBreaker records it as a failure, you can do the following:

[source,java,indent=0]
----
Supplier<String> supplier = () -> {
            throw new RuntimeException("BAM!");
        };
Supplier<String> supplierWithRecovery = SupplierUtils.recover(supplier, (exception) -> "Hello Recovery");
String result = circuitBreaker.executeSupplier(supplierWithRecovery);
assertThat(result).isEqualTo("Hello Recovery");
----

`SupplierUtils` and `CallableUtils` contain other methods like `andThen` which can take can be used to chain functions:

[source,java,indent=0]
----
Supplier<String> supplierWithResultAndExceptionHandler = SupplierUtils.andThen(supplier, (result, exception) -> "Hello Recovery");

Supplier<HttpResponse> supplier = () -> httpClient.doRemoteCall();
Supplier<String> supplierWithResultHandling = SupplierUtils.andThen(supplier, result -> {
    if (result.getStatusCode() == 400) {
       throw new ClientException();
    } else if (result.getStatusCode() == 500) {
       throw new ServerException();
    });
HttpResponse httpResponse = circuitBreaker.executeSupplier(supplierWithResultHandling);
----

===== Recover from an exception after call

If you want to recover from an exception after the CircuitBreaker recorded it as a failure, you can chain the method `Try.recover()`. The recovery method is only invoked, if `Try.of()` returns a `Failure<Throwable>` Monad.

[source,java,indent=0]
----
include::../../../../../resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeRecoverFunction]
----

===== Customize the exception handler

The default exception predicate counts all type of exceptions as failures and triggers the CircuitBreaker. If you want to use a custom exception predicate, you have to implement the functional interface `Predicate` which has a method `test`. The Predicate must return true if the exception should count as a failure, otherwise it must return false.
The following example shows how to ignore an `IOException`, but all other exception types still count as failures.

[source,java,indent=0]
----
include::../../../../../resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java[tags=shouldNotRecordIOExceptionAsAFailure]
----

===== Consume emitted CircuitBreakerEvents

A `CircuitBreakerEvent` can be a state transition, a circuit breaker reset, a successful call, a recorded error or an ignored error. All events contains additional information like event creation time and processing duration of the call. If you want to consume events, you have to register an event consumer.

[source,java]
----
circuitBreaker.getEventPublisher()
    .onSuccess(event -> logger.info(...))
    .onError(event -> logger.info(...))
    .onIgnoredError(event -> logger.info(...))
    .onReset(event -> logger.info(...))
    .onStateTransition(event -> logger.info(...));
// Or if you want to register a consumer listening to all events, you can do:
circuitBreaker.getEventPublisher()
    .onEvent(event -> logger.info(...));
----

You could use the `CircularEventConsumer` to store events in a circular buffer with a fixed capacity.

[source,java]
----
CircularEventConsumer<CircuitBreakerEvent> ringBuffer = new CircularEventConsumer<>(10);
circuitBreaker.getEventPublisher().onEvent(ringBuffer);
List<CircuitBreakerEvent> bufferedEvents = ringBuffer.getBufferedEvents()
----

You can use RxJava or Spring Reactor Adapters to convert the `EventPublisher` into a Reactive Stream. The advantage of a Reactive Stream is that you can use RxJava's `observeOn` operator to specify a different Scheduler that the CircuitBreaker will use to send notifications to its observers/consumers.

[source,java]
----
RxJava2Adapter.toFlowable(circuitBreaker.getEventPublisher())
    .filter(event -> event.getEventType() == Type.ERROR)
    .cast(CircuitBreakerOnErrorEvent.class)
    .subscribe(event -> logger.info(...))
----

==== Monitoring

The CircuitBreaker provides an interface to monitor the current metrics.

[source,java]
----
CircuitBreaker.Metrics metrics = circuitBreaker.getMetrics();
// Returns the current failure rate in percentage.
float failureRate = metrics.getFailureRate();
// Returns the current number of buffered calls.
int bufferedCalls = metrics.getNumberOfBufferedCalls();
// Returns the current number of failed calls.
int failedCalls = metrics.getNumberOfFailedCalls();
// Returns the current number of not permitted calls when the CircuitBreaker is open.
int failedCalls = metrics.getNumberOfNotPermittedCalls();
----

