=== RateLimiter

==== Introduction

The RateLimiter API is very similar to CircuitBreaker.
So it also have in-memory RateLimiterRegistry and RateLimiterConfig where you can configure:

* the period of limit refresh, after each period rate limiter sets its permissions count to `limitForPeriod` value.
* the permissions limit for refresh period.
* the default wait for permission duration.

==== Examples
[source,java]
----
// For example you want to restrict the calling rate of some method to be not higher than 10 req/ms.
RateLimiterConfig config = RateLimiterConfig.custom()
    .limitRefreshPeriod(Duration.ofMillis(1))
    .limitForPeriod(10)
    .timeoutDuration(Duration.ofMillis(25))
    .build();

// Create registry
RateLimiterRegistry rateLimiterRegistry = RateLimiterRegistry.of(config);

// Use registry
RateLimiter rateLimiterWithDefaultConfig = rateLimiterRegistry.rateLimiter("backend");
RateLimiter rateLimiterWithCustomConfig = rateLimiterRegistry.rateLimiter("backend#2", config);

// Or create RateLimiter directly
RateLimiter rateLimiter = RateLimiter.of("NASDAQ :-)", config);
----

===== Use a RateLimiter

As you can guess RateLimiter has all sort of higher order decorator functions just like CircuitBreaker.

[source,java]
----
// Decorate your call to BackendService.doSomething()
CheckedRunnable restrictedCall = RateLimiter
    .decorateCheckedRunnable(rateLimiter, backendService::doSomething);

Try.run(restrictedCall)
    .andThenTry(restrictedCall)
    .onFailure((RequestNotPermitted throwable) -> LOG.info("Wait before call it again :)"));
----

===== Dynamic rate limiter reconfiguration

You can use `changeTimeoutDuration` and `changeLimitForPeriod` methods to change rate limiter params in runtime.

[source,java]
----
// Decorate your call to BackendService.doSomething()
CheckedRunnable restrictedCall = RateLimiter
    .decorateCheckedRunnable(rateLimiter, backendService::doSomething);

Try.run(restrictedCall)
    .andThenTry(restrictedCall)
    .onFailure((RequestNotPermitted throwable) -> LOG.info("Wait before call it again :)"));

// durring second refresh cycle limiter will get 100 permissions
rateLimiter.changeLimitForPeriod(100);
----

New timeout duration won't affect threads that are currently waiting for permission.
New limit won't affect current period permissions and will apply only from next one.

===== RateLimiter and RxJava

The following example shows how to decorate an Observable by using the custom RxJava operator.

[source,java]
----
RateLimiter rateLimiter = RateLimiter.ofDefaults("backendName");
Observable.fromCallable(backendService::doSomething)
    .compose(RateLimiterOperator.of(rateLimiter))
----

Other reactive types (Flowable, Single, Maybe and Completable) are also supported.

===== RateLimiter and Reactor

The following example shows how to decorate a Mono by using the custom Reactor operator.

[source,java]
----
RateLimiter rateLimiter = RateLimiter.ofDefaults("backendName");
Mono.fromCallable(backendService::doSomething)
    .compose(RateLimiterOperator.of(rateLimiter))
----

Flux is also supported.

===== Consume emitted RateLimiterEvents

The RateLimiter emits a stream of RateLimiterEvents. An event can be a successful permission acquire or acquire failure.
All events contains additional information like event creation time and rate limiter name.
If you want to consume events, you have to register an event consumer.

[source,java]
----
rateLimiter.getEventPublisher()
    .onSuccess(event -> logger.info(...))
    .onFailure(event -> logger.info(...));
----

You can use RxJava or Spring Reactor Adapters to convert the `EventPublisher` into a Reactive Stream.

[source,java]
----
RxJava2Adapter.toFlowable(rateLimiter.getEventPublisher())
    .filter(event -> event.getEventType() == FAILED_ACQUIRE)
    .subscribe(event -> logger.info(...))
----

==== Monitoring

The RateLimiter provides simple an interface to monitor the current limiter.
Also AtomicRateLimiter has some enhanced Metrics with some implementation specific details.

[source,java]
----
RateLimiter limit;
RateLimiter.Metrics metrics = limit.getMetrics();
int numberOfThreadsWaitingForPermission = metrics.getNumberOfWaitingThreads();
// Estimates count of available permissions. Can be negative if some permissions where reserved.
int availablePermissions = metrics.getAvailablePermissions();

AtomicRateLimiter atomicLimiter;
// Estimated time duration in nanos to wait for the next permission
long nanosToWaitForPermission = atomicLimiter.getNanosToWait();
----


===== Low level API

If you're interested in making your own thing on top of Resilience4j RateLimiter you'll possibly be interested in
our lower level APIs like `getPermission` and `reservePermission` methods.

===== Thread interruption

You can interrupt threads that are blocked or waiting inside rate limiters.
Our implementations don't throw `InterruptedException`, but set `Thread.isInterrupted` status into true,
 so you are responsible for handling this state in your client code.
In the case where we should interrupt the positive flow of code after `Thread.interrupt'ion
 we throw `AcquirePermissionCancelledException` that is extended from IllegalStateException
 to preserve backward compatibility with version 1.0.0 of Resilience4j.
