=== Retry

==== Set-Up

You can also retry a failed function and recover from the exception, if the maximum retry count was reached. You can create a `Retry` context using a default configuration as follows.

[source,java]
----
// Create a Retry context with a default global configuration
// (maxAttempts = 3, waitDurationInOpenState = 500[ms])
Retry retry = Retry.ofDefaults("id");
----

In order to create a custom-configured `Retry`, you can use the RetryConfig builder. You can configure the maximum number of retry attempts and the wait duration between successive attempts. Furthermore, you can configure a custom Predicate which evaluates if an exception should trigger a retry.

[source,java]
----
RetryConfig config = RetryConfig.custom()
    .maxAttempts(2)
    .waitDuration(Duration.ofMillis(100))
    .retryOnResult(response -> response.getStatus() == 500)
    .retryOnException(e -> e instanceof HelloWorldException)
    .retryExceptions(IOException.class, TimeoutException.class)
    .ignoreExceptions(BunsinessException.class, OtherBunsinessException.class)
    .build();
----

==== Examples

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `Retry.decorateCheckedSupplier()`, `Retry.decorateCheckedRunnable()` or `Retry.decorateCheckedFunction()`.

[source,java]
----
// Given I have a HelloWorldService which throws an exception
HelloWorldService  helloWorldService = mock(HelloWorldService.class);
given(helloWorldService.sayHelloWorld()).willThrow(new HelloWorldException());

// Create a Retry with default configuration
Retry retry = Retry.ofDefaults("id");
// Decorate the invocation of the HelloWorldService
CheckedFunction0<String> retryableSupplier = Retry.decorateCheckedSupplier(retry, helloWorldService::sayHelloWorld);

// When I invoke the function
Try<String> result = Try.of(retryableSupplier).recover((throwable) -> "Hello world from recovery function");

// Then the helloWorldService should be invoked 3 times
BDDMockito.then(helloWorldService).should(times(3)).sayHelloWorld();
// and the exception should be handled by the recovery function
assertThat(result.get()).isEqualTo("Hello world from recovery function");
----

===== Retry and RxJava

The following example shows how to decorate an Observable by using the custom RxJava transformer.

[source,java]
----
Retry retry = Retry.ofDefaults("backendName");
Observable.fromCallable(backendService::doSomething)
    .compose(RetryTransformer.of(retry))
----

===== Retry and Reactor

The following example shows how to decorate a Flux or Mono by using the custom Reactor Operator.

[source,java]
----
Retry retry = Retry.ofDefaults("backendName");
Mono.fromCallable(backendService::doSomething)
    .compose(RetryOperator.of(retry))
----

===== Consume emitted RetryEvents

The Retry emits a stream of RetryEvents. An event can be a failure which signals that even all retries have failed or success if a retry was successful.

[source,java]
----
retry.getEventPublisher()
    .onSuccess(event -> logger.info(...))
    .onError(event -> logger.info(...));
----
