=== TimeLimiter

==== Introduction

The TimeLimiter API sets a time limit on the execution of a supplied future. The decorated supplied
future can be chained with a CircuitBreaker to trip the circuit breaker if the supplied
future's timeout has exceeded.

The TimeLimiter provides the flexibility to handle custom future implementations such as ones that
can cancel its execution gracefully. The TimeLimiter by default is configured to cancel the future
if an exception occurs. This is configurable within the configuration.

==== Examples
[source,java]
----
// For example, you want to restrict the execution of a long running task to 60 seconds.
TimeLimiterConfig config = TimeLimiterConfig.custom()
    .timeoutDuration(Duration.ofSeconds(60))
    .cancelRunningFuture(true)
    .build();

// Create TimeLimiter
TimeLimiter timeLimiter = TimeLimiter.of(config);
----

===== Using a TimeLimiter

TimeLimiter takes a Future Supplier and returns a Callable that will unwrap the Future and attempt
to retrieve the future's value within the configured timeout period. If the timeout is reached, then
an exception is thrown upstream and TimeLimiter, if configured, will attempt to cancel the future.

[source,java]
----
// Run your call to BackendService.doSomething() asynchronously
Supplier<CompletableFuture<Integer>> futureSupplier = () -> CompletableFuture.supplyAsync(backendService::doSomething);

// Either execute the future
Integer result = timeLimiter.executeFutureSupplier(futureSupplier);

// Or decorate your supplier so that the future can be retrieved and executed upon
Callable restrictedCall = TimeLimiter
    .decorateFutureSupplier(timeLimiter, futureSupplier);

Try.of(restrictedCall::call)
    .onFailure(throwable -> LOG.info("A timeout possibly occurred."));
----

===== TimeLimiter and CircuitBreaker

The following example shows how to apply a time limit to a circuit breaker callable.

[source,java]
----
Supplier<CompletableFuture<Integer>> futureSupplier = () -> CompletableFuture.supplyAsync(backendService::doSomething);

Callable restrictedCall = TimeLimiter
    .decorateFutureSupplier(timeLimiter, futureSupplier);

// Decorate the restricted callable with a CircuitBreaker
Callable chainedCallable = CircuitBreaker.decorateCallable(circuitBreaker, restrictedCall);

Try.of(chainedCallable::call)
    .onFailure(throwable -> LOG.info("We might have timed out or the circuit breaker has opened."));
----
