= resilience4j-prometheus

Direct integration of circuit breaker and rate limiter metrics with
https://github.com/prometheus/client_java[Prometheus simple client]

For the circuit breaker library exports 2 metrics:

1. By state with default metric name `circuit_breaker_states` and label `state`:

    - `closed`
    - `open`
    - `half_open`

2. By call result with default metric name `circuit_breaker_calls` and label `call_result`:

    - `successful`
    - `failed`
    - `not_permitted`
    - `buffered`
    - `buffered_max`

For the rate limiter following metric with default name `rate_limiter` and label `param` exported:

- `available_permissions`
- `waiting_threads`

The names of the rate limiters and circuit breakers are exposed using label `name`.

== Usage

=== CircuitBreaker

[source,java]
--
final CollectorRegistry registry = new CollectorRegistry();

final CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();

final CircuitBreaker foo = circuitBreakerRegistry.circuitBreaker("foo");
final CircuitBreaker boo = circuitBreakerRegistry.circuitBreaker("boo");

// Registering metrics in prometeus CollectorRegistry
new CircuitBreakerExports(circuitBreakerRegistry).register(registry);
--

=== RateLimiter

[source,java]
--
final CollectorRegistry registry = new CollectorRegistry();

final RateLimiterRegistry rateLimiterRegistry = CircuitBreakerRegistry.ofDefaults();

final RateLimiter foo = rateLimiterRegistry.rateLimiter("foo");
final RateLimiter boo = rateLimiterRegistry.rateLimiter("boo");

// Registering metrics in prometeus CollectorRegistry
new RateLimiterExports(rateLimiterRegistry).register(registry);
--

For both it is possible to use just a collection of breakers and limiters instead of registry.

== License

Copyright 2017 Oleksandr Goldobin

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
