== Usage Guide

=== Create a CircuitBreaker

This library comes with an in-memory `CircuitBreakerRegistry` based on a `ConcurrentHashMap` which provides thread safety and atomicity guarantees. You must use the CircuitBreakerRegistry to manage (create and retrieve) your CircuitBreakers. You can create a CircuitBreakerRegistry with a default global `CircuitBreakerConfig` for all of your CircuitBreakers as follows.

[source,java,indent=0]
----
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
----

As an alternative you can provide your own custom global `CircuitBreakerConfig`. In order to create a custom global CircuitBreakerConfig or a CircuitBreakerConfig for a specific CircuitBreaker, you can use the CircuitBreakerConfig builder. You can configure:

* the failure rate threshold in percentage above which the CircuitBreaker should trip open and start short-circuiting calls
* the wait duration which specifies how long the CircuitBreaker should stay open, before it switches to half open
* the size of the ring buffer when the CircuitBreaker is half open
* the size of the ring buffer when the CircuitBreaker is closed
* a custom CircuitBreakerEventListener which handles CircuitBreaker events
* a custom Predicate which evaluates if an exception should be recorded as a failure and thus increase the failure rate

[source,java,indent=0]
----
// Create a custom configuration for a CircuitBreaker
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
    .failureRateThreshold(50)
    .waitDurationInOpenState(Duration.ofMillis(1000))
    .ringBufferSizeInHalfOpenState(2)
    .ringBufferSizeInClosedState(2)
    .build();

// Create a CircuitBreakerRegistry with a custom global configuration
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);

// Get a CircuitBreaker from the CircuitBreakerRegistry with the global default configuration
CircuitBreaker circuitBreaker2 = circuitBreakerRegistry.circuitBreaker("otherName");

// Get a CircuitBreaker from the CircuitBreakerRegistry with a custom configuration
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);
----

=== Use a CircuitBreaker

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `CircuitBreaker.decorateCheckedSupplier()`, `CircuitBreaker.decorateCheckedRunnable()` or `CircuitBreaker.decorateCheckedFunction()`.
You can invoke the decorated function with `Try.of(...)` or `Try.run(...)` from https://github.com/javaslang/javaslang[Javaslang]. This allows to chain further functions with `map`, `flatMap`, `filter`, `recover` or `andThen`. The chained functions are only invoked, if the CircuitBreaker is CLOSED or HALF_OPEN.
In the following example, `Try.of(...)` returns a `Success<String>` Monad, if the invocation of the function is successful. If the function throws an exception, a `Failure<Throwable>` Monad is returned and `map` is not invoked.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeMap]
----

You can also chain up functions which are decorated by different CircuitBreakers.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldChainDecoratedFunctions]
----

=== OPEN CircuitBreaker example

In this example `map` is not invoked, because the CircuitBreaker is OPEN. The call to `Try.of` returns a `Failure<Throwable>` Monad so that the chained function is not invoked.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldThrowCircuitBreakerOpenException]
----

=== Recover from an exception

If you want to recover from any exception, you can chain the method `Try.recover()`. The recovery method is only invoked, if `Try.of()` returns a `Failure<Throwable>` Monad.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeRecoverFunction]
----

=== Customize the exception handler
The default exception handler counts all type of exceptions as failures and triggers the CircuitBreaker. If you want to use a custom exception handler, you have to implement the functional interface `Predicate` which has a method `test`. The Predicate must return true if the exception should count as a failure, otherwise it must return false.
The following example shows how to ignore an `IOException`, but all other exception types still count as failures.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldNotRecordIOExceptionAsAFailure]
----

=== Observe the event stream
A CircuitBreaker publishes a stream of CircuitBreakerEvents to any Observer/Consumer who subscribes. This library uses RxJava to to provide this functionality.
If you want to consume events, you have to subscribe to the event stream. This library provides a consumer `CircuitBreakerEventConsumer` which can be used to store events in a circular buffer with a fixed capacity.
You can use RxJava to filter certain events.

[source,java]
----
CircuitBreakerEventConsumer ringBuffer = new CircuitBreakerEventConsumer(10);
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");
circuitBreaker.observeCircuitBreakerEvents()
                .filter(event -> event.getEventType() == Type.RECORDED_FAILURE)
                .subscribe(ringBuffer);
----

=== Retry a failed function

You can also retry a failed function and recover from the exception, if the maximum retry count was reached. You can create a `Retry` context using a default configuration as follows.

[source,java]
----
// Create a Retry context with a default global configuration
// (maxAttempts = 3, waitDurationInOpenState = 500[ms])
Retry retryContext = Retry.ofDefaults();
----

In order to create a custom `Retry` context, you can use the Retry context builder. You can configure the maximum number of retry attempts and the wait duration between successive attempts. Furthermore, you can configure a custom Predicate which evaluates if an exception should trigger a retry.

[source,java]
----
Retry retryContext = Retry.custom()
    .maxAttempts(2)
    .waitDurationInOpenState(Duration.ofMillis(100))
    .retryOnException(throwable -> Match.of(throwable)
        .whenType(WebServiceException.class).then(false)
        .otherwise(true).get())
    .build();
----

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `Retry.decorateCheckedSupplier()`, `Retry.decorateCheckedRunnable()` or `Retry.decorateCheckedFunction()`.

[source,java]
----
// Given I have a HelloWorldService which throws an exception
HelloWorldService  helloWorldService = mock(HelloWorldService.class);
given(helloWorldService.sayHelloWorld()).willThrow(new WebServiceException("BAM!"));

// Create a Retry with default configuration
Retry retryContext = Retry.ofDefaults();
// Decorate the invocation of the HelloWorldService
Try.CheckedSupplier<String> retryableSupplier = Retry.decorateCheckedSupplier(helloWorldService::sayHelloWorld, retryContext);

// When I invoke the function
Try<String> result = Try.of(retryableSupplier).recover((throwable) -> "Hello world from recovery function");

// Then the helloWorldService should be invoked 3 times
BDDMockito.then(helloWorldService).should(times(3)).sayHelloWorld();
// and the exception should be handled by the recovery function
assertThat(result.get()).isEqualTo("Hello world from recovery function");
----

=== Use a CompletableFuture

You can also invoke a decorated function asynchronously by using a `CompletableFuture` and chain further functions.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeAsyncApply]
----

=== Use Reactive Streams

You can also invoke a decorated function asynchronously by using a Reactive Streams implementation like https://github.com/ReactiveX/RxJava[RxJava] or https://github.com/reactor/reactor/[Project Reactor].

[source,java]
----
 // Given
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("testName");
// CircuitBreaker is initially CLOSED
circuitBreaker.recordFailure(new RuntimeException());
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED);
// CircuitBreaker is still CLOSED, because 1 failure is allowed
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.CLOSED);
circuitBreaker.recordFailure(new RuntimeException());
// CircuitBreaker is OPEN, because maxFailures > 1
assertThat(circuitBreaker.getState()).isEqualTo(CircuitBreaker.State.OPEN);

// Decorate the supplier of the HelloWorldService with CircuitBreaker functionality
Supplier<String> supplier = CircuitBreaker.decorateSupplier(() -> "Hello world", circuitBreaker);

//When I consume from a reactive stream it should forward the CircuitBreakerOpenException.
Streams.generate(supplier::get)
        .map(value -> value + " from reactive streams")
        .consume(value -> {
            LOG.info(value);
        }, exception -> {
            LOG.info("Exception handled: " + exception.toString());
            assertThat(exception).isInstanceOf(CircuitBreakerOpenException.class);
        });
----
