== Usage Guide

=== Create a CircuitBreaker

This library comes with an in-memory `CircuitBreakerRegistry` based on a `ConcurrentHashMap` which provides thread safety and atomicity guarantees. You can use the CircuitBreakerRegistry to manage (create and retrieve) CircuitBreaker instances. You can create a CircuitBreakerRegistry with a default global `CircuitBreakerConfig` for all of your CircuitBreaker instances as follows.

[source,java,indent=0]
----
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
----

As an alternative you can provide your own custom global `CircuitBreakerConfig`. In order to create a custom global CircuitBreakerConfig or a CircuitBreakerConfig for a specific CircuitBreaker, you can use the CircuitBreakerConfig builder. You can configure:

* the failure rate threshold in percentage above which the CircuitBreaker should trip open and start short-circuiting calls
* the wait duration which specifies how long the CircuitBreaker should stay open, before it switches to half open
* the size of the ring buffer when the CircuitBreaker is half open
* the size of the ring buffer when the CircuitBreaker is closed
* a custom CircuitBreakerEventListener which handles CircuitBreaker events
* a custom Predicate which evaluates if an exception should be recorded as a failure and thus increase the failure rate

[source,java,indent=0]
----
// Create a custom configuration for a CircuitBreaker
CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
    .failureRateThreshold(50)
    .waitDurationInOpenState(Duration.ofMillis(1000))
    .ringBufferSizeInHalfOpenState(2)
    .ringBufferSizeInClosedState(2)
    .build();

// Create a CircuitBreakerRegistry with a custom global configuration
CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);

// Get a CircuitBreaker from the CircuitBreakerRegistry with the global default configuration
CircuitBreaker circuitBreaker2 = circuitBreakerRegistry.circuitBreaker("otherName");

// Get a CircuitBreaker from the CircuitBreakerRegistry with a custom configuration
CircuitBreaker circuitBreaker = circuitBreakerRegistry.circuitBreaker("uniqueName", circuitBreakerConfig);
----

If you don't want to use the CircuitBreakerRegistry to manage CircuitBreaker instances, you can also create instances directly:

[source,java,indent=0]
----
CircuitBreaker defauktCircuitBreaker = CircuitBreaker.ofDefaults("testName");

CircuitBreaker customCircuitBreaker = CircuitBreaker.of("testName", circuitBreakerConfig);
----

=== Use a CircuitBreaker

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `CircuitBreaker.decorateCheckedSupplier()`, `CircuitBreaker.decorateCheckedRunnable()` or `CircuitBreaker.decorateCheckedFunction()`.
You can invoke the decorated function with `Try.of(...)` or `Try.run(...)` from https://github.com/javaslang/javaslang[Javaslang]. This allows to chain further functions with `map`, `flatMap`, `filter`, `recover` or `andThen`. The chained functions are only invoked, if the CircuitBreaker is CLOSED or HALF_OPEN.
In the following example, `Try.of(...)` returns a `Success<String>` Monad, if the invocation of the function is successful. If the function throws an exception, a `Failure<Throwable>` Monad is returned and `map` is not invoked.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeMap]
----

You can also chain up functions which are decorated by different CircuitBreakers.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldChainDecoratedFunctions]
----

=== OPEN CircuitBreaker example

In this example `map` is not invoked, because the CircuitBreaker is OPEN. The call to `Try.of` returns a `Failure<Throwable>` Monad so that the chained function is not invoked.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldThrowCircuitBreakerOpenException]
----

=== Recover from an exception

If you want to recover from any exception, you can chain the method `Try.recover()`. The recovery method is only invoked, if `Try.of()` returns a `Failure<Throwable>` Monad.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeRecoverFunction]
----

=== Customize the exception handler
The default exception handler counts all type of exceptions as failures and triggers the CircuitBreaker. If you want to use a custom exception handler, you have to implement the functional interface `Predicate` which has a method `test`. The Predicate must return true if the exception should count as a failure, otherwise it must return false.
The following example shows how to ignore an `IOException`, but all other exception types still count as failures.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldNotRecordIOExceptionAsAFailure]
----

=== Subscribe to the CircuitBreakerEvent stream
A CircuitBreaker publishes a stream of CircuitBreakerEvents. An event can be a state transition or a recorded error. This library uses RxJava to to provide this functionality.
If you want to consume events, you have to subscribe to the event stream. This library provides a consumer `CircuitBreakerEventConsumer` which can be used to store events in a circular buffer with a fixed capacity.
You can use RxJava to filter the events.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/consumer/CircuitBreakerEventConsumerTest.java[tags=shouldBufferEvents]
----

== Monitor CircuitBreaker metrics

The CircuitBreaker provides an interface to monitor the current metrics.

[source,java]
----
CircuitBreaker.Metrics metrics = circuitBreaker.getMetrics();
// Returns the failure rate in percentage.
float failureRate = metrics.getFailureRate();
// Returns the current number of buffered calls.
int bufferedCalls = metrics.getNumberOfBufferedCalls();
// Returns the current number of failed calls.
int failedCalls = metrics.getNumberOfFailedCalls();
----

=== Retry a failed function

You can also retry a failed function and recover from the exception, if the maximum retry count was reached. You can create a `Retry` context using a default configuration as follows.

[source,java]
----
// Create a Retry context with a default global configuration
// (maxAttempts = 3, waitDurationInOpenState = 500[ms])
RetryConfig config = RetryConfig.custom()
    .maxAttempts(3)
    .waitDuration(Duration.ofMillis(500))
    .build();
Retry retryContext = Retry.of("id", config);
----

In order to create a custom `Retry` context, you can use the Retry context builder. You can configure the maximum number of retry attempts and the wait duration between successive attempts. Furthermore, you can configure a custom Predicate which evaluates if an exception should trigger a retry.

[source,java]
----
RetryConfig config = RetryConfig.custom()
    .maxAttempts(2)
    .waitDurationInOpenState(Duration.ofMillis(100))
    .retryOnException(throwable -> Match.of(throwable)
        .whenType(WebServiceException.class).then(false)
        .otherwise(true).get())
    .build();
----

You can decorate any `Supplier / Runnable / Function` or `CheckedSupplier / CheckedRunnable / CheckedFunction` function with `Retry.decorateCheckedSupplier()`, `Retry.decorateCheckedRunnable()` or `Retry.decorateCheckedFunction()`.

[source,java]
----
// Given I have a HelloWorldService which throws an exception
HelloWorldService  helloWorldService = mock(HelloWorldService.class);
given(helloWorldService.sayHelloWorld()).willThrow(new WebServiceException("BAM!"));

// Create a Retry with default configuration
Retry retryContext = Retry.ofDefaults("id");
// Decorate the invocation of the HelloWorldService
Try.CheckedSupplier<String> retryableSupplier = Retry.decorateCheckedSupplier(retryContext, helloWorldService::sayHelloWorld);

// When I invoke the function
Try<String> result = Try.of(retryableSupplier).recover((throwable) -> "Hello world from recovery function");

// Then the helloWorldService should be invoked 3 times
BDDMockito.then(helloWorldService).should(times(3)).sayHelloWorld();
// and the exception should be handled by the recovery function
assertThat(result.get()).isEqualTo("Hello world from recovery function");
----

=== Use a CompletableFuture

You can also invoke a decorated function asynchronously by using a `CompletableFuture` and chain further functions.

[source,java,indent=0]
----
include::../../test/java/javaslang/circuitbreaker/CircuitBreakerTest.java[tags=shouldInvokeAsyncApply]
----

=== Use RxJava

You can protect any RxJava Observable or Flowable by using the custom CircuitBreakerOperator.

[source,java]
----
CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("testName");
Observable.fromCallable(helloWorldService::sayHelloWorld)
    .lift(CircuitBreakerOperator.of(circuitBreaker))
----

=== Create a RateLimiter

The RateLimiter API is very similar to CircuitBreaker.
So it also have in-memory RateLimiterRegistry and RateLimiterConfig where you can configure:

* the period of limit refresh, after each period rate limiter sets its permissions count to `limitForPeriod` value.
* the permissions limit for refresh period.
* the default wait for permission duration.

[source,java]
----
// For example you want to restrict the calling rate of some method to be not higher than 10 req/ms.
RateLimiterConfig config = RateLimiterConfig.builder()
    .limitRefreshPeriod(Duration.ofMillis(1))
    .limitForPeriod(10)
    .timeoutDuration(Duration.ofMillis(25))
    .build();

// Create registry
RateLimiterRegistry rateLimiterRegistry = RateLimiterRegistry.of(config);

// Use registry
RateLimiter reateLimiterWithDefaultConfig = rateLimiterRegistry.rateLimiter("backend");
RateLimiter reateLimiterWithCustomConfig = rateLimiterRegistry.rateLimiter("backend#2", config);

// Or create RateLimiter directly
RateLimiter rateLimiter = RateLimiter.of("NASDAQ :-)", config);
----

=== Use a RateLimiter
As you can gues RateLimiter has all sort of higher order decorator functions just like CircuitBreaker.

[source,java]
----
// Decorate your call to BackendService.doSomething()
Try.CheckedRunnable restrictedCall = RateLimiter
    .decorateCheckedRunnable(rateLimiter, backendService::doSomething);

Try.run(restrictedCall)
    .andThenTry(restrictedCall)
    .onFailure((RequestNotPermitted throwable) -> LOG.info("Wait before call it again :)"));
----

== Monitor RateLimiter metrics

The RateLimiter provides simple an interface to monitor the current limiter.
Also AtomicRateLimiter has some enhanced Metrics with some implementation specific details.

[source,java]
----
RateLimiter limit;
RateLimiter.Metrics metrics = limit.getMetrics();
int numberOfThreadsWaitingForPermission = metrics.getNumberOfWaitingThreads();
// Estimates count of available permissions. Can be negative if some permissions where reserved.
int availablePermissions = metrics.getAvailablePermissions();

AtomicRateLimiter atomicLimiter;
// Estimated time duration in nanos to wait for the next permission
long nanosToWaitForPermission = atomicLimiter.getNanosToWait();
----