== Getting started

The projects requires JDK 8. The project is published in JCenter and Maven Central.
If you use Gradle or Maven, you can include Resilience4j modules as follows.

WARNING: The *groupId* has been changed from *io.github.robwin* to *io.github.resilience4j*

Resilience provides several core modules and add-on modules:

Core modules:

* resilience4j-circuitbreaker: Circuit breaking
* resilience4j-ratelimiter: Rate limiting
* resilience4j-bulkhead: Bulkheading
* resilience4j-retry: Automatic retrying
* resilience4j-cache: Response caching

Add-on modules

* resilience4j-metrics: Dropwizard Metrics exporter
* resilience4j-prometheus: Prometheus Metrics exporter
* resilience4j-spring-boot: Spring Boot Starter
* resilience4j-ratpack: Ratpack Starter
* resilience4j-retrofit: Retrofit Call Adapter Factories
* resilience4j-vertx: Vertx Future decorator
* resilience4j-consumer: Circular Buffer Event consumer

=== Gradle

==== Release
[source,groovy, subs="attributes"]
----
repositories {
    jCenter()
}

compile "io.github.resilience4j:resilience4j-circuitbreaker:{release-version}"
compile "io.github.resilience4j:resilience4j-ratelimiter:{release-version}"
compile "io.github.resilience4j:resilience4j-retry:{release-version}"
compile "io.github.resilience4j:resilience4j-bulkhead:{release-version}"
compile "io.github.resilience4j:resilience4j-cache:{release-version}"
----

==== Snapshot

[source,groovy]
----
repositories {
   maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
}
----

=== Maven
==== Release

[source,xml, subs="specialcharacters,attributes"]
----
<repositories>
    <repository>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>jcenter-releases</id>
        <name>jcenter</name>
        <url>http://jcenter.bintray.com</url>
    </repository>
</repositories>

<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-circuitbreaker</artifactId>
    <version>{release-version}</version>
</dependency>
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-ratelimiter</artifactId>
    <version>{release-version}</version>
</dependency>
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-retry</artifactId>
    <version>{release-version}</version>
</dependency>
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-bulkhead</artifactId>
    <version>{release-version}</version>
</dependency>
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-cache</artifactId>
    <version>{release-version}</version>
</dependency>
----

==== Snapshot

[source,java]
----
<repositories>
    <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
</repositories>
----
