== Introduction

Resilience4j is a lightweight, easy-to-use fault tolerance library inspired by https://github.com/Netflix/Hystrix[Netflix Hystrix], but designed for Java 8 and functional programming. Lightweight, because the library only uses http://www.vavr.io/[Vavr (formerly Javaslang)], which does not have any other external library dependencies. Netflix Hystrix, in contrast, has a compile dependency to https://github.com/Netflix/archaius[Archaius] which has many more external library dependencies such as Guava and Apache Commons Configuration.
With Resilience4j you don't have to go all-in, you can pick what you need.

Resilience provides several core modules and add-on modules:

Core modules:

* resilience4j-circuitbreaker: Circuit breaking
* resilience4j-ratelimiter: Rate limiting
* resilience4j-bulkhead: Bulkheading
* resilience4j-retry: Automatic retrying (sync and async)
* resilience4j-cache: Response caching
* resilience4j-timelimiter: Timeout handling

Add-on modules

* resilience4j-reactor: Custom Spring Reactor operator
* resilience4j-rxjava2: Custom RxJava2 operator
* resilience4j-micrometer: Micrometer Metrics exporter
* resilience4j-metrics: Dropwizard Metrics exporter
* resilience4j-prometheus: Prometheus Metrics exporter
* resilience4j-spring-boot: Spring Boot Starter
* resilience4j-spring-boot2: Spring Boot 2 Starter
* resilience4j-ratpack: Ratpack Starter
* resilience4j-retrofit: Retrofit adapter
* resilience4j-feign: Feign adapter
* resilience4j-vertx: Vertx Future decorator
* resilience4j-kotlin: Kotlin coroutines support
* resilience4j-consumer: Circular Buffer Event consumer

To highlight a few differences to Netflix Hystrix:

* In Hystrix calls to external systems have to be wrapped in a HystrixCommand. This library, in contrast, provides higher-order functions (decorators) to enhance any functional interface, lambda expression or method reference with a http://martinfowler.com/bliki/CircuitBreaker.html[Circuit Breaker], Rate Limiter or Bulkhead. Furthermore, the library provides decorators to retry failed calls or cache call results. You can stack more than one decorator on any functional interface, lambda expression or method reference. That means, you can combine a Bulkhead, RateLimiter and Retry decorator with a CircuitBreaker decorator. The advantage is that you have the choice to select the decorator you need and nothing else. Any decorated function can be executed synchronously or asynchronously by using a CompletableFuture or RxJava.
* Hystrix, by default, stores execution results in 10 1-second window buckets. If a 1-second window bucket is passed, a new bucket is created and the oldest is dropped. This library stores execution results in Ring Bit Buffer without a statistical rolling time window. A successful call is stored as a 0 bit and a failed call is stored as a 1 bit. The Ring Bit Buffer has a configurable fixed-size and stores the bits in a long[] array which is saving memory compared to a boolean array. That means the Ring Bit Buffer only needs an array of 16 long (64-bit) values to store the status of 1024 calls. The advantage is that this CircuitBreaker works out-of-the-box for low and high frequency backend systems, because execution results are not dropped when a time window is passed.
* Hystrix only performs a single execution when in half-open state to determine whether to close a CircuitBreaker. This library allows to perform a configurable number of executions and compares the result against a configurable threshold to determine whether to close a CircuitBreaker.
* This library provides custom RxJava operators to decorate any `Observable` or `Flowable` with a Circuit Breaker, Bulkhead or Ratelimiter.
* Hystrix and this library emit a stream of events which are useful to system operators to monitor metrics about execution outcomes and latency.

