= resilience4j-ratpack

This project provides a sample application using the resilience4j https://ratpack.io[Ratpack] integation.

For detailed documentation look at our *http://resilience4j.github.io/resilience4j/#_ratpack_starter[Usage Guide]*

== Usage

```
git clone git@github.com:resilience4j/resilience4j.git
cd resilience4j/resilience4j-ratpack-demo
../gradlew run
```

== Features

The sample application demonstrates the following features:

* Circuitbreaker annotations
* Properties-based configuration
* Metrics
* Actuator endpoints
```
curl localhost:5050/circuitbreaker/states
curl localhost:5050/circuitbreaker/events
```

== License

Copyright 2019 Dan Maas

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
