=== Dropwizard Metrics exporter

==== Introduction

Integration with http://metrics.dropwizard.io[Dropwizard Metrics].
With this add-on you can easily add your bulkhead, circuit breaker, rate limiter, retry metrics in your Dropwizard `MetricRegistry`.

==== Usage

===== Bulkhead

[source,java]
--
final MetricRegistry collectorRegistry = new MetricRegistry();

final BulkheadRegistry bulkheadRegistry = BulkheadRegistry.ofDefaults();
final Bulkhead foo = bulkheadRegistry.bulkhead("foo");
final Bulkhead boo = bulkheadRegistry.bulkhead("boo");

// you can register all bulkheads at once
collectorRegistry.registerAll(BulkheadMetrics.ofBulkheadRegistry(bulkheadRegistry));
// or register them one by one
collectorRegistry.registerAll(BulkheadMetrics.ofBulkhead(foo));
--

For each bulkhead this registry will export:

* `available_concurrent_calls` - instantaneous read of the number of currently available concurrent calls `[int]`
* `max_allowed_concurrent_calls` - maximum number of allowed concurrent calls `[int]`

===== CircuitBreaker

[source,java]
--
final MetricRegistry collectorRegistry = new MetricRegistry();

final CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
final CircuitBreaker foo = circuitBreakerRegistry.circuitBreaker("foo");
final CircuitBreaker boo = circuitBreakerRegistry.circuitBreaker("boo");

// you can register all circuit breakers at once
collectorRegistry.registerAll(CircuitBreakerMetrics.ofCircuitBreakerRegistry(circuitBreakerRegistry));
// or register them one by one
collectorRegistry.registerAll(CircuitBreakerMetrics.ofCircuitBreaker(foo));

// there is some additional useful methods in CircuitBreakerMetrics class
--

For each circuit breaker this registry will export:

* `state` - instantaneous read of the current state where 0-CLOSED, 1-OPEN, 2-HALF-OPEN `[int]`
* `successful` - current number of successful calls `[int]`
* `failed` - current number of failed calls `[int]`
* `slow` - current number of slow calls `[int]`
* `buffered` - current number of buffered calls `[int]`
* `not_permitted` - current number of not permitted calls `[int]`
* `failure_rate` - current failure rate `[float]`
* `slow_call_rate` - current slow call rate `[float]`

===== RateLimiter

[source,java]
--
final MetricRegistry metricRegistry = new MetricRegistry();
final RateLimiterRegistry rateLimiterRegistry = RateLimiterRegistry.ofDefaults();
final RateLimiter rateLimiter = rateLimiterRegistry.rateLimiter("testLimit");

// you can register all rate limiters at once
metricRegistry.registerAll(RateLimiterMetrics.ofRateLimiterRegistry(rateLimiterRegistry));
// or register them one by one
metricRegistry.registerAll(RateLimiterMetrics.ofRateLimiter(rateLimiter));
--

For each rate limiter this registry will export:

* `available_permissions` - current number of available permissions `[int]`
* `number_of_waiting_threads` - current number of threads waiting for permission `[int]`

===== Retry

[source,java]
--
final MetricRegistry metricRegistry = new MetricRegistry();
final RetryRegistry retryRegistry = RetryRegistry.ofDefaults();
final Retry retry = retryRegistry.retry("testLimit");

// you can register all rate limiters at once
metricRegistry.registerAll(RetryMetrics.ofRetryRegistry(retryRegistry));
// or register them one by one
metricRegistry.registerAll(RetryMetrics.ofRetry(retry));
--

For each retry this registry will export:

* `successful_calls_without_retry` - the number of successful calls without a retry attempt `[long]`
* `successful_calls_with_retry` - the number of successful calls after a retry attempt `[long]`
* `failed_calls_without_retry` - the number of failed calls without a retry attempt `[long]`
* `failed_calls_with_retry` - the number of failed calls after all retry attempts `[long]`

