=== Prometheus Metrics Integration

==== Introduction

Integration with https://github.com/prometheus/client_java[Prometheus simple client]

This add-on provides Prometheus collectors for `CircuitBreaker`, `RateLimiter` and `Bulkhead` metrics.

==== Usage

===== CircuitBreaker

[source,java]
--
final CollectorRegistry collectorRegistry = CollectorRegistry.defaultRegistry;

final CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();

final CircuitBreaker foo = circuitBreakerRegistry.circuitBreaker("foo");
final CircuitBreaker boo = circuitBreakerRegistry.circuitBreaker("boo");

// Registering metrics in prometeus CollectorRegistry
collectorRegistry.register(CircuitBreakerMetricsCollector.ofCircuitBreakerRegistry(circuitBreakerRegistry));
--

===== RateLimiter

[source,java]
--
final CollectorRegistry collectorRegistry = CollectorRegistry.defaultRegistry;

final RateLimiterRegistry rateLimiterRegistry = RateLimiterRegistry.ofDefaults();

final RateLimiter foo = rateLimiterRegistry.rateLimiter("foo");
final RateLimiter boo = rateLimiterRegistry.rateLimiter("boo");

// Registering metrics in prometeus CollectorRegistry
collectorRegistry.register(RateLimiterMetricsCollector.ofRateLimiterRegistry(rateLimiterRegistry));
--

===== Bulkhead

[source,java]
--
final CollectorRegistry collectorRegistry = CollectorRegistry.defaultRegistry;

final BulkheadRegistry bulkheadRegistry = BulkheadRegistry.ofDefaults();

final Bulkhead foo = bulkheadRegistry.bulkhead("foo");
final Bulkhead boo = bulkheadRegistry.bulkhead("boo");

// Registering metrics in prometeus CollectorRegistry
collectorRegistry.register(BulkheadMetricsCollector.ofBulkheadRegistry(rateLimiterRegistry));
--