=== Ratpack Starter

This add-on provides integration with https://ratpack.io[Ratpack] libraries.

==== Gradle

Add the Ratpack Starter of Resilience4j to your compile dependency:

```
repositories {
	maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
	mavenCentral()
}


dependencies {
	compile('io.github.resilience4j:resilience4j-ratpack:{release-version}')
}
```

==== Basic Usage

Installing the `Resilience4jModule` module provides a `CircuitBreakerRegistry`, `RateLimiterRegistry`,
and `RetryRegistry` with the default configurations. It also install the Guice method interceptors
for CircuitBreakers, RateLimiters, and Retries. Finally, it allows configuration of metrics
and even the building of CircuitBreakers, RateLimiters, and Retries. See below for configuration details.

Note: If you don't register a `CircuitBreakerRegistry` or `RateLimiterRegistry` or `RetryRegistry`, the defaults
will be used.

For example

[source,java]
----
public class MyModule extends AbstractModule {

    @Override
    protected void configure() {
        CircuitBreakerConfig config = CircuitBreakerConfig.custom();
        bind(CircuitBreakerRegistry.class).toInstance(CircuitBreakerRegistry.of(config);
        install(Resilience4jModule.class);
    }
}
----

==== Handlers

You can rate limit an endpoint by defining a `RateLimiterHandler` for the endpoint.

This will only rate limit the `/` endpoint.
[source,groovy]
----
ratpack {
            bindings {
                bindInstance(RateLimiterRegistry, RateLimiterRegistry.ofDefaults())
                module(Resilience4jModule)
            }
            handlers {
                get(new RateLimiterHandler(registry, 'test'))
                get {
                    render 'success'
                }
                get('a') {
                    render 'success'
                }
            }
        }
----

This will rate limit all endpoints against the same `RateLimiter`.
[source,groovy]
----
ratpack {
            bindings {
                bindInstance(RateLimiterRegistry, RateLimiterRegistry.ofDefaults())
                module(Resilience4jModule)
            }
            handlers {
                all(new RateLimiterHandler(registry, 'test'))
                get {
                    render 'success'
                }
                get('a') {
                    render 'success'
                }
            }
        }
----

==== Promises

Ratpack promises provide the means by which an application can become fully non-blocking and asynchronous.
Resilience4j provides transformers that can be applied to Promises. This is ideal when promising a value
that is coming from some sort of I/O source.

===== CircuitBreaker

You can easily apply a CircuitBreaker to any Ratpack Promise.

[source,java]
----
public Promise<String> methodWhichReturnsAPromise() {
    return backendBConnector.methodWhichReturnsAPromise()
            .transform(CircuitBreakerTransformer.of(circuitBreaker).recover(t -> "recovered"));
}
----

===== Retry

You can easily apply a Retry to any Ratpack Promise.

[source,java]
----
public Promise<String> methodWhichReturnsAPromise() {
    return backendBConnector.methodWhichReturnsAPromise()
            .transform(RetryTransformer.of(retry).recover(t -> "recovered"));
}
----

===== RateLimiter

You can easily apply a RateLimiter to any Ratpack Promise.

[source,java]
----
public Promise<String> methodWhichReturnsAPromise() {
    return backendBConnector.methodWhichReturnsAPromise()
            .transform(RateLimiterTransformer.of(rateLimiter).recover(t -> "recovered"));
}
----

==== Guice AOP

Guice provides method interception capabilities. Here are provided some annotations which support
methods returning types:

* Promise
* CompletionStage
* object values
* Observable
* Flowable
* Single

===== CircuitBreaker
The demo shows how to use the `CircuitBreaker` annotation to make your Ratpack application more fault tolerant.
You can either annotate a class in order to protect all public methods or just some specific methods.
For example:

[source,java]
----
@CircuitBreaker(name = "backendA", recovery = MyRecoveryFunction.class)
@Singleton
public class BackendAConnector implements Connector {
    ...
}
----
Where `MyRecoveryFunction` is implements `io.github.resilience4j.ratpack.RecoveryFunction` and provides
a fallback value that is returned when the circuit breaker identified by `name` is open.

===== Retry
The demo shows how to use the `Retry` annotation to make your Ratpack application more fault tolerant.
You can either annotate a class in order to protect all public methods or just some specific methods.
For example:
`
[source,java]
----
@Retry(name = "backendA", recovery = MyRecoveryFunction.class)
@Singleton
public class BackendAConnector implements Connector {
    ...
}
----
Where `MyRecoveryFunction` is implements `io.github.resilience4j.ratpack.RecoveryFunction` and provides
a fallback value that is returned when the retry identified by `name` is has exceeded it's max calls.

===== RateLimiter
The demo shows how to use the `RateLimiter` annotation to make your Ratpack application more fault tolerant.
You can either annotate a class in order to protect all public methods or just some specific methods.
For example:

[source,java]
----
@RateLimiter(name = "backendA", recovery = MyRecoveryFunction.class)
@Singleton
public class BackendAConnector implements Connector {
    ...
}
----
Where `MyRecoveryFunction` is implements `io.github.resilience4j.ratpack.RecoveryFunction` and provides
a fallback value that is returned when the rate limiter rate limit identified by `name` is exceeded.

==== Functional style

You can still use a functional programming style for CircuitBreaker, Retry, and RateLimiter. For example:

[source,java]
----
@Singleton
public class BusinessBService implements BusinessService  {

    public Try<String> methodWithRecovery() {
        CheckedFunction0<String> backendFunction = CircuitBreaker.decorateCheckedSupplier(circuitBreaker, () -> backendBConnector.failure());
        return Try.of(backendFunction)
                .recover((throwable) -> recovery(throwable));
    }

    private String recovery(Throwable throwable) {
        // Handle exception and invoke fallback
        return "Hello world from recovery";
    }

}
----

==== Adding CircuitBreakers, RateLimiters, and Retries
These can be defined in the module configuration or in an external configuration.
Note that the module only provide default registries, which you can replace by
binding your own.

Module configuration example:

[source,java]
----
public class MyModule extends AbstractModule {

    @Override
    protected void configure() {
        Resilience4jModule module = new Resilience4jModule();
        module.configure(c -> c
            .circuitBreaker("test1", cb -> cb
                .defaults(true)
            ).circuitBreaker("test2", cb -> cb
                .failureRateThreshold(50)
                .waitIntervalInMillis(5000)
                .ringBufferSizeInClosedState(200)
                .ringBufferSizeInHalfOpenState(20)
            ).rateLimiter("test1", cb -> cb
                .defaults(true)
            ).rateLimiter("test2", cb -> cb
                .limitForPeriod(100)
                .limitRefreshPeriodInNanos(500)
                .timeoutInMillis(10)
            ).retry("test1", cb -> cb
                .defaults(true)
            ).retry("test2", cb -> cb
                .maxAttempts(3)
                .waitDurationInMillis(1000)
            )
        );
        install(module);
    }
}
----

External configuration example:

[source,groovy]
----
ratpack {
    serverConfig {
        yaml(getClass().classLoader.getResource('application.yml'))
        require("/resilience4j", Resilience4jConfig)
    }
    bindings {
        module(Resilience4jModule)
    }
    handlers {
        get {
            render 'ok'
        }
    }
}
----

[source,yaml]
----
resilience4j:
    circuitBreakers:
        test1:
            defaults: true
        test2:
            ringBufferSizeInClosedState: 200
            ringBufferSizeInHalfOpenState: 20
            waitInterval: 5000
            failureRateThreshold: 50
    rateLimiters:
        test1:
            defaults: true
        test2:
            limitForPeriod: 100
            limitRefreshPeriodInNanos: 500
            timeoutInMillis: 10
    retries:
        test1:
            defaults: true
        test2:
            maxAttempts: 3
            waitDurationInMillis: 1000
----

==== Metrics
Both dropwizard and prometheus metrics can be auto configured and enabled for all registered
circuitbreaker instances, ratelimiter instances, and retry instances.

For dropwizard metrics to work, add a compile dependency on resilience4j-metrics and
bind a MetricRegistry instance.

For prometheus metrics to work, add a compile dependency on resilience4j-prometheus and
bind a CollectorRegistry instance.

Enabling Dropwizard Metrics:

[source,java]
----
public class MyModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(MetricRegistry.class);
        Resilience4jModule module = new Resilience4jModule();
        module.configure(c -> c.metrics(true));
        install(module);
    }
}
----

Enabling Prometheus Metrics:

[source,java]
----
public class MyModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(CollectorRegistry.class);
        Resilience4jModule module = new Resilience4jModule();
        module.configure(c -> c.prometheus(true));
        install(module);
    }
}
----



==== Monitoring
TODO
Ratpack provides the concept of a health check. See https://ratpack.io/manual/current/api/ratpack/health/HealthCheckHandler.html for details.
CircuitBreaker, RateLimiter, and Retry health checks have not been implemented yet.
When implemented they should function similarly to the spring boot health checks.

==== CircuitBreaker Event Monitoring
TODO
Handlers for displaying the last X CircuitBreaker, Ratelimiter, or Retry events are not yet implemented.
When implemented they should function similarly to the spring boot management endpoints.

