=== Spring Boot Starter

==== Gradle

Add the Spring Boot Starter of Resilience4j to your compile dependency:

```
repositories {
	maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
	mavenCentral()
}


dependencies {
	compile('io.github.resilience4j:resilience4j-spring-boot:{release-version}')
}
```

==== Monitoring

Spring Boot Actuator health information can be used to check the status of your running application.
It is often used by monitoring software to alert someone if a production system has serious issues.

==== Retry
When you enable retry , the service calls that has retry/ async retry annotation, it will publish the status
and metrics via custom `RetryHealthIndicator`  and `AsyncRetryHealthIndicator`

For example :
[source,json]
----
 "retryBackendARetry": {
      "status": "UP",
      "details": {
        "failedCallsWithoutRetry": "0%",
        "failedCallsWithRetry": 1,
        "successCalls": 1,
        "successCallsWithRetry": 0
      }
    },
    "retryBackendAAsyncRetry": {
      "status": "UP",
      "details": {
        "failedCallsWithoutRetry": "0%",
        "failedCallsWithRetry": 0,
        "successCalls": 0,
        "successCallsWithRetry": 0
      }
    }
----
Metrics are automatically published on the Metrics endpoint.
For example:

[source,json]
----
{
    "names": [
        "resilience4j.retry.backendA.failedCallsWithoutRetry",
        "resilience4j.retry.backendA.failedCallsWithRetry",
        "resilience4j.retry.backendA.successCalls",
        "resilience4j.retry.backendA.successCallsWithRetry",
        "resilience4j.asyncRetry.backendA.failedCallsWithoutRetry",
        "resilience4j.asyncRetry.backendB.failedCallsWithRetry",
        "resilience4j.asyncRetry.backendB.successCalls",
        "resilience4j.asyncRetry.backendB.successCallsWithRetry"
        ]
}
----

When you want to publish Retry/AsyncRetry endpoints on the Prometheus endpoint, you have to add the dependency `io.micrometer:micrometer-registry-prometheus`.
and you have same metrics exposed there , check circuit breaker below for more information about the example.

==== CircuitBreaker
This demo publishes the status and metrics of all CircuitBreakers via a custom `CircuitBreakerHealthIndicator`.
A closed CircuitBreaker state is mapped to UP, an open state to DOWN and a half-open state to UNKNOWN.

For example:

[source,json]
----
{
  "status": "UP",
  "backendACircuitBreaker": {
    "status": "DOWN",
    "failureRate": "60.0%",
    "failureRateThreshold": "50.0%",
    "maxBufferedCalls": 5,
    "bufferedCalls": 5,
    "failedCalls": 3,
    "notPermittedCalls": 0
  },
  "backendBCircuitBreaker": {
    "status": "UP",
    "failureRate": "0.0%",
    "failureRateThreshold": "50.0%",
    "maxBufferedCalls": 10,
    "bufferedCalls": 10,
    "failedCalls": 0,
    "notPermittedCalls": 0
  }
}
----

When you want to publish CircuitBreaker metrics on the Metrics endpoint, you can add `resilience4j-metrics` to register metrics in a Dropwizard Metrics Registry.
For example:

[source,json]
----
{
    "resilience4j.circuitbreaker.backendA.successful": 2,
    "resilience4j.circuitbreaker.backendA.failed": 3,
    "resilience4j.circuitbreaker.backendA.buffered": 5,
    "resilience4j.circuitbreaker.backendA.buffered_max": 5,
    "resilience4j.circuitbreaker.backendA.not_permitted": 7,
    "resilience4j.circuitbreaker.backendB.successful": 0,
    "resilience4j.circuitbreaker.backendB.failed": 0,
    "resilience4j.circuitbreaker.backendB.buffered": 0,
    "resilience4j.circuitbreaker.backendB.buffered_max": 10,
    "resilience4j.circuitbreaker.backendB.not_permitted": 0
}
----

When you want to publish CircuitBreaker endpoints on the Prometheus endpoint, you have to add the optional module `resilience4j-prometheus`.
For example:

[source]
----
# HELP resilience4j_circuitbreaker_calls Circuit Breaker Call Stats
# TYPE resilience4j_circuitbreaker_calls gauge
resilience4j_circuitbreaker_calls{name="backendB",call_result="successful",} 0.0
resilience4j_circuitbreaker_calls{name="backendB",call_result="failed",} 0.0
resilience4j_circuitbreaker_calls{name="backendB",call_result="not_permitted",} 0.0
resilience4j_circuitbreaker_calls{name="backendB",call_result="buffered",} 0.0
resilience4j_circuitbreaker_calls{name="backendB",call_result="buffered_max",} 10.0
resilience4j_circuitbreaker_calls{name="backendA",call_result="successful",} 0.0
resilience4j_circuitbreaker_calls{name="backendA",call_result="failed",} 0.0
resilience4j_circuitbreaker_calls{name="backendA",call_result="not_permitted",} 0.0
resilience4j_circuitbreaker_calls{name="backendA",call_result="buffered",} 0.0
resilience4j_circuitbreaker_calls{name="backendA",call_result="buffered_max",} 5.0
# HELP resilience4j_circuitbreaker_states Circuit Breaker States
# TYPE resilience4j_circuitbreaker_states gauge
resilience4j_circuitbreaker_states{name="backendB",state="closed",} 1.0
resilience4j_circuitbreaker_states{name="backendB",state="open",} 0.0
resilience4j_circuitbreaker_states{name="backendB",state="half_open",} 0.0
resilience4j_circuitbreaker_states{name="backendA",state="closed",} 1.0
resilience4j_circuitbreaker_states{name="backendA",state="open",} 0.0
resilience4j_circuitbreaker_states{name="backendA",state="half_open",} 0.0
----

==== RateLimiter
This demo publishes the status and metrics of all RateLimiter via a custom `RateLimiterHealthIndicator`.
RateLimiterHealthIndicator changes its state DOWN only if there is some permission waiting threads
and they won't be able to unblock until timeout.

For example:

[source,json]
----
{
  "status": "UP",
  "backendARateLimiter": {
    "status": "UP",
    "availablePermissions": 10,
    "numberOfWaitingThreads": 0
  }
}
----

You can publish RateLimiter metrics on the Metrics endpoint,
you can add `resilience4j-metrics` to register metrics in a Dropwizard Metrics Registry.
For example:

[source,json]
----
{
    "resilience4j.ratelimiter.backendA.available_permissions": 10,
    "resilience4j.ratelimiter.backendA.number_of_waiting_threads": 0,
    "resilience4j.ratelimiter.backendB.available_permissions": 6,
    "resilience4j.ratelimiter.backendB.number_of_waiting_threads": 0
}
----

==== Configuration

===== Retry
You can configure your Retries in Spring Boot's `application.yml` config file.
For example
[source,yaml]
----
resilience4j.retry:
  retryAspectOrder: 399
  backends:
    retryBackendA:
      maxRetryAttempts: 3
      waitDuration: 600
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
      enableExponentialBackoff: false
      exponentialBackoffMultiplier: 2
      enableRandomizedWait: false
      randomizedWaitFactor: 2
      retryExceptionPredicate: io.github.resilience4j.circuitbreaker.RecordFailurePredicate
      retryExceptions:
      - java.io.IOException
      ignoreExceptions:
      - io.github.resilience4j.circuitbreaker.IgnoredException
----
The rules for Retry configuration :

    - By default the same beck end configuration will be used for sync and async retry configuration if not defined otherwise.
    - enableRandomizedWait and enableExponentialBackoff is false by default.
    - registerHealthIndicator is true by default.
    - You can not enable both enableRandomizedWait and enableExponentialBackoff , validation exception will be thrown if it happen.
    - If exponentialBackoffMultiplier is not provided if enableExponentialBackoff is enabled , default ExponentialBackoff will be used , same story for enableRandomizedWait.

The rules for Retry spring annotation usage  :

    - You can use the same back-end configuration for both sync and async retry if you use both annotations in for the same backed method level wise only ,
     if you mix annotations between class level and method level on the same back-end class , validation exception will be thrown
    - For `AsyncRetry` annotation , please make sure the return type is instance of Java `CompletionStage` otherwise runtime exception will be thrown

Code example of retry and async retry annotation usage in Java Spring component :
[source,java]
----
@component
public class RetryDummyServiceImpl implements RetryDummyService {

@Retry(name = RetryDummyService.BACKEND)
@Override
public void doSomething(boolean throwBackendTrouble) throws IOException {
	if (throwBackendTrouble) {
		throw new IOException("Test Message");
	}
}

@AsyncRetry(name = RetryDummyService.BACKEND)
@Override
public CompletionStage<String> doSomethingAsync(boolean throwException) throws IOException {
	if (throwException) {
		throw new IOException("Test Message");
	} else {
		return CompletableFuture.supplyAsync(() -> "test");
	}
}

}
----
===== CircuitBreaker
You can configure your CircuitBreakers in Spring Boot's `application.yml` config file.
For example

[source,yaml]
----
resilience4j.circuitbreaker:
    backends:
        backendA:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
        backendB:
            ringBufferSizeInClosedState: 10
            ringBufferSizeInHalfOpenState: 5
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
----

===== RateLimiter
You can configure your CircuitBreakers in Spring Boot's `application.yml` config file.
For example

[source,yaml]
----
resilience4j.ratelimiter:
    limiters:
        backendA:
            limitForPeriod: 10
            limitRefreshPeriodInMillis: 1000
            timeoutInMillis: 0
            subscribeForEvents: true
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        backendB:
            limitForPeriod: 6
            limitRefreshPeriodInMillis: 500
            timeoutInMillis: 3000
----

===== Explicit ordering for CircuitBreaker and RateLimiter aspects
You can adjust `RateLimiterProperties.rateLimiterAspectOrder` and `CircuitBreakerProperties.circuitBreakerAspectOrder`
and explicitly define `CircuitBreaker` and `RateLimiter` execution sequence.
By default `CircuitBreaker` will be executed BEFORE `RateLimiter`.

WARNING: Please be careful changing of `CircuitBreaker`/`RateLimiter` ordering can drastically change application behavior.

==== Event Monitoring

===== Retry

The emitted Retry events are stored in a separate circular event consumer buffers. The size of a event consumer buffer can be configured per Retry in the application.yml file (eventConsumerBufferSize).
The demo adds a custom Spring Boot Actuator endpoint which can be used to monitor the emitted events of your Retries.
The endpoint `/management/retries` lists the names of all Retries instances.
For example:
----
{
  "retries": [
    "retryBackendA",
    "retryBackendA"
  ]
}
----

The endpoint `/management/retries/events` lists the latest 100 emitted events of all Retries instances.

----
{
  "retryEvents": [
    {
      "retryName": "retryBackendC",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:49.648+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 1
    },
    {
      "retryName": "retryBackendA",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:50.259+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 2
    },
    {
      "retryName": "retryBackendA",
      "type": "ERROR",
      "creationTime": "2019-03-11T17:32:50.866+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 3
    }
  ]
}
----

The endpoint `/management/retries/events/{retryrName}` lists the latest emitted events of a specific Retry.
For example `/management/retries/events/retryBackendA`:

----
{
  "retryEvents": [
    {
      "retryName": "retryBackendA",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:49.648+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 1
    },
    {
      "retryName": "retryBackendA",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:50.259+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 2
    },
    {
      "retryName": "retryBackendA",
      "type": "ERROR",
      "creationTime": "2019-03-11T17:32:50.866+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 3
    }
  ]
}
----

===== CircuitBreaker

The emitted CircuitBreaker events are stored in a separate circular event consumer buffers. The size of a event consumer buffer can be configured per CircuitBreaker in the application.yml file (eventConsumerBufferSize).
The demo adds a custom Spring Boot Actuator endpoint which can be used to monitor the emitted events of your CircuitBreakers.
The endpoint `/management/circuitbreaker` lists the names of all CircuitBreaker instances.
For example:

----
{
    "circuitBreakers": [
      "backendA",
      "backendB"
    ]
}
----

The endpoint `/management/circuitbreaker/events` lists the latest 100 emitted events of all CircuitBreaker instances.
The endpoint `/management/circuitbreaker/stream/events` streams emitted events of all CircuitBreaker instances using Server-Sent Events.

----
{
"circuitBreakerEvents":[
  {
    "circuitBreakerName": "backendA",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:39:17.117+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "SUCCESS",
    "creationTime": "2017-01-10T15:39:20.518+01:00[Europe/Berlin]",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendB",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:41:31.159+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendB",
    "type": "SUCCESS",
    "creationTime": "2017-01-10T15:41:33.526+01:00[Europe/Berlin]",
    "durationInMs": 0
  }
]
}
----

The endpoint `/management/circuitbreaker/events/{circuitBreakerName}` lists the latest emitted events of a specific CircuitBreaker.
The endpoint `/management/circuitbreaker/stream/events/{circuitBreakerName}` streams emitted events using Server-Sent Events.
For example `/management/circuitbreaker/events/backendA`:

----
{
"circuitBreakerEvents":[
  {
    "circuitBreakerName": "backendA",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:39:17.117+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "SUCCESS",
    "creationTime": "2017-01-10T15:39:20.518+01:00[Europe/Berlin]",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "STATE_TRANSITION",
    "creationTime": "2017-01-10T15:39:22.341+01:00[Europe/Berlin]",
    "stateTransition": "CLOSED_TO_OPEN"
  },
  {
    "circuitBreakerName": "backendA",
    "type": "NOT_PERMITTED",
    "creationTime": "2017-01-10T15:39:22.780+01:00[Europe/Berlin]"
  }
]
}
----

You can even filter the list of  events.
The endpoint `/management/circuitbreaker/events/{circuitBreakerName}/{eventType}` lists the filtered events.
The endpoint `/management/circuitbreaker/stream/events/{circuitBreakerName}/{eventType}` streams emitted events using Server-Sent Events.
Event types can be:

* ERROR: A CircuitBreakerEvent which informs that an error has been recorded.
* IGNORED_ERROR: A CircuitBreakerEvent which informs that an error has been ignored.
* SUCCESS: A CircuitBreakerEvent which informs that a success has been recorded.
* NOT_PERMITTED: A CircuitBreakerEvent which informs that a call was not permitted because the CircuitBreaker state is OPEN.
* STATE_TRANSITION: A CircuitBreakerEvent which informs the state of the CircuitBreaker has been changed.

For example `/management/circuitbreaker/events/backendA/ERROR`:
----
{
"circuitBreakerEvents":[
  {
    "circuitBreakerName": "backendA",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:42:59.324+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:43:22.802+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  }
]
}
----

===== RateLimiter
WARNING: Unlike the CircuitBreaker events, RateLimiter events require explicit subscription.
Use property resilience4j.ratelimiter.limiters.{yourBackendName}.registerHealthIndicator=true

There are literally the same endpoints implemented for RateLimiter,
so for detailed documentation please refer to previous section:

List of available endpoints:

* `/ratelimiter/events`
* `/ratelimiter/stream/events`
* `/ratelimiter/events/{rateLimiterName}`
* `/ratelimiter/stream/events/{rateLimiterName}`
* `/ratelimiter/events/{rateLimiterName}/{eventType}`
* `/ratelimiter/stream/events/{rateLimiterName}/{eventType}`

Example of response:
----
{
  "eventsList": [
    {
      "rateLimiterName": "backendA",
      "rateLimiterEventType": "SUCCESSFUL_ACQUIRE",
      "rateLimiterCreationTime": "2017-05-05T21:29:40.463+03:00[Europe/Uzhgorod]"
    },
    {
      "rateLimiterName": "backendA",
      "rateLimiterEventType": "SUCCESSFUL_ACQUIRE",
      "rateLimiterCreationTime": "2017-05-05T21:29:40.469+03:00[Europe/Uzhgorod]"
    },
    {
      "rateLimiterName": "backendA",
      "rateLimiterEventType": "FAILED_ACQUIRE",
      "rateLimiterCreationTime": "2017-05-05T21:29:41.268+03:00[Europe/Uzhgorod]"
    }
  ]
}
----
