=== Spring Boot 2 Starter

==== Gradle

Add the Spring Boot 2 Starter of Resilience4j to your compile dependency.
You also need Spring Boot Actuator and Spring Boot AOP.

[source,groovy, subs="attributes"]
----
repositories {
	maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
	mavenCentral()
}


dependencies {
	compile('io.github.resilience4j:resilience4j-spring-boot2:{release-version}')
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('org.springframework.boot:spring-boot-starter-aop')
}
----

==== Supported Types by Spring boot starter resilience aspects

RateLimiter, Retry, CircuitBreaker and Bulkhead annotations support synchronous return types, asynchronous types like CompletableFutures and reactive types like RxJava2 and Reactor.

==== Monitoring

Spring Boot Actuator health information can be used to check the status of your running application.
It is often used by monitoring software to alert someone if a production system has serious issues.

==== CircuitBreaker
The starter publishes the status and metrics of all CircuitBreakers via a custom `CircuitBreakerHealthIndicator`.
By default, none of the circuit breaker status will map to an unhealthy state. This behaviour can be changed using the `allowHealthIndicatorToFail` property. When set to true, the circuit breaker health indicator will report DOWN when it's open.

For example:

[source,json]
----
{
  "status": "UP",
  "backendACircuitBreaker": {
    "status": "DOWN",
    "failureRate": "60.0%",
    "failureRateThreshold": "50.0%",
    "maxBufferedCalls": 5,
    "bufferedCalls": 5,
    "failedCalls": 3,
    "notPermittedCalls": 0
  },
  "backendBCircuitBreaker": {
    "status": "UP",
    "failureRate": "0.0%",
    "failureRateThreshold": "50.0%",
    "maxBufferedCalls": 10,
    "bufferedCalls": 10,
    "failedCalls": 0,
    "notPermittedCalls": 0
  }
}
----

Metrics are automatically published on the Metrics endpoint.
To retrieve the names of the available metrics, make a GET request to `/actuator/metrics`.
Please see https://docs.spring.io/spring-boot/docs/current/actuator-api/html/#metrics[Actuator Metrics documentation] for more details.

For example:

[source,json]
----
{
    "names": [
        "resilience4j.circuitbreaker.calls",
        "resilience4j.circuitbreaker.max.buffered.calls",
        "resilience4j.circuitbreaker.buffered.calls",
        "resilience4j.circuitbreaker.state",
        "resilience4j.circuitbreaker.failure.rate"
        ]
}
----

To retrieve a metric, make a GET request to `/actuator/metrics/{metric.name}`.
For example: `/actuator/metrics/resilience4j.circuitbreaker.calls`

[source,json]
----
{
    "name": "resilience4j.circuitbreaker.calls",
    "measurements": [
        {
            "statistic": "VALUE",
            "value": 3
        }
    ],
    "availableTags": [
        {
            "tag": "kind",
            "values": [
                "not_permitted",
                "successful",
                "failed"
            ]
        },
        {
            "tag": "name",
            "values": [
                "backendB",
                "backendA"
            ]
        }
    ]
}
----

When you want to publish CircuitBreaker endpoints on the Prometheus endpoint, you have to add the dependency `io.micrometer:micrometer-registry-prometheus`.
To retrieve metrics, make a GET request to `/actuator/prometheus`.

[source]
----
resilience4j_circuitbreaker_calls{kind="not_permitted",name="backendA",} 0.0
resilience4j_circuitbreaker_calls{kind="not_permitted",name="backendB",} 0.0
resilience4j_circuitbreaker_calls{kind="successful",name="backendA",} 5.0
resilience4j_circuitbreaker_calls{kind="successful",name="backendB",} 8.0
resilience4j_circuitbreaker_calls{kind="failed",name="backendB",} 2.0
resilience4j_circuitbreaker_calls{kind="failed",name="backendA",} 5.0

resilience4j_circuitbreaker_state{name="backendA",} 0.0
resilience4j_circuitbreaker_state{name="backendB",} 0.0

resilience4j_circuitbreaker_failure_rate{name="backendA",} 50.0
resilience4j_circuitbreaker_failure_rate{name="backendB",} 20.0

resilience4j_circuitbreaker_max_buffered_calls{name="backendA",} 10.0
resilience4j_circuitbreaker_max_buffered_calls{name="backendB",} 10.0

resilience4j_circuitbreaker_buffered_calls{name="backendA",} 10.0
resilience4j_circuitbreaker_buffered_calls{name="backendB",} 10.0
----

==== Retry
Metrics are automatically published on the metrics endpoint.

For example:

[source,json]
----
{
    "names": [
        "resilience4j.retry.calls"
        ]
}
----

To retrieve the metric, make a GET request to `/actuator/metrics/{metric.name}`.
For example: `/actuator/metrics/resilience4j.retry.calls`

[source,json]
----
{
    "name": "resilience4j.retry.calls",
    "measurements": [
        {
            "statistic": "VALUE",
            "value": 7
        }
    ],
    "availableTags": [
        {
            "tag": "kind",
            "values": [
                "successful.without.retry",
                "successful.with.retry",
                "failed.with.retry",
                "failed.without.retry"
            ]
        },
        {
            "tag": "name",
            "values": [
                "backendB",
                "backendA"
            ]
        }
    ]
}
----

When you want to publish Retry/AsyncRetry endpoints on the Prometheus endpoint, you have to add the dependency `io.micrometer:micrometer-registry-prometheus`.
and you have same metrics exposed there , check circuit breaker below for more information about the example.

==== Bulkhead

Metrics are automatically published on the Metrics endpoint.

For example:

[source,json]
----
{
    "names": [
        "resilience4j.bulkhead.available.concurrent.calls",
        "resilience4j.bulkhead.max.allowed.concurrent.calls"
        ]
}
----

To retrieve the metric, make a GET request to `/actuator/metrics/{metric.name}`.
For example: `/actuator/metrics/resilience4j.bulkhead.available.concurrent.calls`

[source,json]
----
{
    "name": "resilience4j.bulkhead.available.concurrent.calls",
    "measurements": [
        {
            "statistic": "VALUE",
            "value": 3
        }
    ],
    "availableTags": [
        {
            "tag": "name",
            "values": [
                "backendB",
                "backendA"
            ]
        }
    ]
}
----

==== RateLimiter
The starter the status and metrics of all RateLimiter via a custom `RateLimiterHealthIndicator`.
By default, none of the rate limiter status will map to an unhealthy state. This behaviour can be changed using the `allowHealthIndicatorToFail` property.
When set to true, the rate limiter health indicator will report DOWN if there is some permission waiting threads and they won't be able to unblock until timeout.

For example:

[source,json]
----
{
  "status": "UP",
  "backendARateLimiter": {
    "status": "UP",
    "availablePermissions": 10,
    "numberOfWaitingThreads": 0
  }
}
----

Metrics are automatically published on the Metrics endpoint.
For example:

[source,json]
----
{
    "names": [
        "resilience4j.ratelimiter.available.permissions",
        "resilience4j.ratelimiter.waiting.threads"
        ]
}
----

To retrieve the metric, make a GET request to `/actuator/metrics/{metric.name}`.
For example: `/actuator/metrics/resilience4j.ratelimiter.available.permissions`

[source,json]
----
{
    "name": "resilience4j_ratelimiter.available.permissions",
    "measurements": [
        {
            "statistic": "VALUE",
            "value": 50
        }
    ],
    "availableTags": [
        {
            "tag": "name",
            "values": [
                "backendA"
            ]
        }
    ]
}
----

==== Configuration

===== Retry
You can configure your Retries in Spring Boot's `application.yml` config file.
For example
[source,yaml]
----
resilience4j.retry:
  retryAspectOrder: 399
  backends:
    retryBackendA:
      maxRetryAttempts: 3
      waitDuration: 600
      eventConsumerBufferSize: 100
      enableExponentialBackoff: false
      exponentialBackoffMultiplier: 2
      enableRandomizedWait: false
      randomizedWaitFactor: 2
      retryExceptionPredicate: io.github.resilience4j.circuitbreaker.RecordFailurePredicate
      retryExceptions:
      - java.io.IOException
      ignoreExceptions:
      - io.github.resilience4j.circuitbreaker.IgnoredException
----
The rules for Retry configuration :

    - enableRandomizedWait and enableExponentialBackoff is false by default.
    - You can not enable both enableRandomizedWait and enableExponentialBackoff , validation exception will be thrown if it happen.
    - If exponentialBackoffMultiplier is not provided if enableExponentialBackoff is enabled , default ExponentialBackoff will be used , same story for enableRandomizedWait.

The rules for Retry spring annotation usage  :

    - Retry aspect will detect the proper handling based into the method return type for synchronous , asynchronous execution(CompletableFuture) , RxJava2 and Reactor
    - Fallback support is enabled by defining name of fallback method in @Retry
[source,java]
----
            @Retry(name = BACKEND, fallbackMethod = "fallback")
            public String sync(String param1) {
                return "test";
            }

            private String fallback(String param1, IllegalStateException e) {
                return "test";
            }
----
    - Its important to remember that Retry method and its fallback method should be placed in the same class and have same method signature (optional parameter for failed execution exception).
    - If there are multiple fallbackMethod methods, one of the methods that has most closest superclass parameter of thrown object will be invoked, for example:
[source,java]
----
            @Retry(name = BACKEND, fallbackMethod = "fallback")
            public String sync(String param1) {
                return "test";
            }

            private String fallback(String param1, IllegalArgumentException e) {
                return "test";
            }

            private String fallback(String param1, RuntimeException e) {
                 return "test";
            }
----
and if you try to recover from  NumberFormatException, the method with signature String fallback(String parameter, IllegalArgumentException exception)} will be invoked.

Code example of Sync, Async, Reactive retry annotation usage in Java Spring component :
[source,java]
----
@Component
@Retry(name = RetryDummyService.BACKEND)
public class RetryDummyServiceImpl implements RetryDummyService {


@Override
public void doSomething(boolean throwBackendTrouble) throws IOException {
	if (throwBackendTrouble) {
		throw new IOException("Test Message");
	}
}


@Override
public CompletionStage<String> doSomethingAsync(boolean throwException) throws IOException {
    if (throwException) {
    	CompletableFuture<String> promise = new CompletableFuture<>();
    	promise.completeExceptionally(new IOException("Test Message"));
    	return promise;
    } else {
    	return CompletableFuture.supplyAsync(() -> "test");
    }
}

@Override
public Flux<String> doSomethingFlux(boolean throwException) {
	if (throwException) {
		return Flux.error(new IllegalArgumentException("FailedFlux"));
	}
		return Flux.fromArray(Arrays.array("test", "test2"));
	}
}

@Override
public Flowable<String> doSomethingFlowable(boolean throwException) {
	if (throwException) {
		return Flowable.error(new IllegalArgumentException("Failed"));
	}
	    return Flowable.just("testMaybe");
	}
}

}
----

Beyond the config file configuration, the Spring Bean configuration is now using @ConditionalOnMissingBean to allow for overriding default behavior.
These Beans can be overridden in your application's Spring Bean configuration:

* RetryRegistry
* RetryAspect
* EventConsumerRegistry<RetryEvent>
* RxJava2RetryAspectExt
* ReactorRetryAspectExt

Note that in Spring Boot 1.x, EventConsumerRegistry<RetryEvent> cannot be overridden because of limitations of the @ConditionalOnMissingBean implementation.
To override this, go to at least Spring Boot 2.1.x.

===== CircuitBreaker
You can configure your CircuitBreakers in Spring Boot's `application.yml` config file.
For example

[source,yaml]
----
resilience4j.circuitbreaker:
    backends:
        backendA:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            allowHealthIndicatorToFail: false
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
        backendB:
            ringBufferSizeInClosedState: 10
            ringBufferSizeInHalfOpenState: 5
            waitInterval: 5000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            allowHealthIndicatorToFail: false
            recordFailurePredicate: com.foo.FooRecordFailurePredicate
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
            ignoreExceptions:
                - org.springframework.web.client.HttpClientErrorException
----

You can also override/partial-override/share default configuration for your CircuitBreakers in Spring Boot's `application.yml` config file.
For example

[source,yaml]
----
resilience4j.circuitbreaker:
    configs:
        default:
            writableStackTraceEnabled: false
            ringBufferSizeInClosedState: 100
            ringBufferSizeInHalfOpenState: 10
            waitInterval: 10000
            failureRateThreshold: 60
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            allowHealthIndicatorToFail: false
    backends:
        backendA:
            baseConfig: default
        backendB:
            baseConfig: default
----

Beyond the config file configuration, the Spring Bean configuration is now using @ConditionalOnMissingBean to allow for overriding default behavior.
These Beans can be overridden in your application's Spring Bean configuration:

* CircuitBreakerRegistry
* CircuitBreakerAspect
* RxJava2CircuitBreakerAspectExt
* ReactorCircuitBreakerAspectExt
* EventConsumerRegistry<CircuitBreakerEvent>


The rules for CircuitBreaker spring annotation usage  :

    - CircuitBreaker aspect with fallback support will detect the proper handling based into the method return type for synchronous , asynchronous execution(CompletableFuture) , RxJava2 and Reactor
    - Fallback support is enabled by defining name of fallback method in @CircuitBreaker

[source,java]
----
    @CircuitBreaker(name = BACKEND, fallbackMethod = "fallback")
    public String sync() {
        return "test";
    }
----

    - Its important to remember that CircuitBreaker method and its fallback method should be placed in the same class and have same method signature (optional parameter for failed execution exception).
    - If there are multiple fallbackMethod methods, one of the methods that has most closest superclass parameter of thrown object will be invoked, for example:
[source,java]
----
                @CircuitBreaker(name = BACKEND, fallbackMethod = "fallback")
                public String sync(String param1) {
                    return "test";
                }

                private String fallback(String param1, IllegalArgumentException e) {
                    return "test";
                }

                private String fallback(String param1, RuntimeException e) {
                     return "test";
                }
----
and if you try to recover from  NumberFormatException, the method with signature String fallback(String parameter, IllegalArgumentException exception) will be invoked.

===== RateLimiter
You can configure your CircuitBreakers in Spring Boot's `application.yml` config file.
For example

[source,yaml]
----
resilience4j.ratelimiter:
    limiters:
        backendA:
            limitForPeriod: 10
            limitRefreshPeriodInMillis: 1000
            timeoutInMillis: 0
            subscribeForEvents: true
            registerHealthIndicator: true
            allowHealthIndicatorToFail: false
            eventConsumerBufferSize: 100
        backendB:
            limitForPeriod: 6
            limitRefreshPeriodInMillis: 500
            timeoutInMillis: 3000
----

Beyond the config file configuration, the Spring Bean configuration is now using @ConditionalOnMissingBean to allow for overriding default behavior.
These Beans can be overridden in your application's Spring Bean configuration:

* RateLimiterRegistry
* RateLimiterAspect
* EventConsumerRegistry<RateLimiterEvent>
* RxJava2RateLimiterAspectExt
* ReactorRateLimiterAspectExt

The rules for RateLimiter spring annotation usage  :

    - RateLimiter aspect with fallback support will detect the proper handling based into the method return type for synchronous , asynchronous execution(CompletableFuture) , RxJava2 and Reactor
    - Fallback support is enabled by defining name of fallback method in @RateLimiter

[source,java]
----
    @RateLimiter(name = BACKEND, fallbackMethod = "fallback")
    public String sync() {
        return "test";
    }
----

    - Its important to remember that RateLimiter method and its fallback method should be placed in the same class and have same method signature (optional parameter for failed execution exception).
    - If there are multiple fallbackMethod methods, one of the methods that has most closest superclass parameter of thrown object will be invoked, for example:
[source,java]
----
                @RateLimiter(name = BACKEND, fallbackMethod = "fallback")
                public String sync(String param1) {
                    return "test";
                }

                private String fallback(String param1, IllegalArgumentException e) {
                    return "test";
                }

                private String fallback(String param1, RuntimeException e) {
                     return "test";
                }
----
and if you try to recover from  NumberFormatException, the method with signature String fallback(String parameter, IllegalArgumentException exception) will be invoked.

===== Explicit ordering for CircuitBreaker and RateLimiter aspects
You can adjust `RateLimiterProperties.rateLimiterAspectOrder` and `CircuitBreakerProperties.circuitBreakerAspectOrder`
and explicitly define `CircuitBreaker` and `RateLimiter` execution sequence.
By default `CircuitBreaker` will be executed BEFORE `RateLimiter`.

WARNING: Please be careful changing of `CircuitBreaker`/`RateLimiter` ordering can drastically change application behavior.

==== Event Monitoring

===== Retry

The emitted Retry events are stored in a separate circular event consumer buffers. The size of a event consumer buffer can be configured per Retry in the application.yml file (eventConsumerBufferSize).
The demo adds a custom Spring Boot Actuator endpoint which can be used to monitor the emitted events of your Retries.
The endpoint `/actuator/retries` lists the names of all Retries instances.
For example:
----
{
  "retries": [
    "retryBackendA",
    "retryBackendA"
  ]
}
----

The endpoint `/actuator/retriesevents` lists the latest 100 emitted events of all Retries instances.

----
{
  "retryEvents": [
    {
      "retryName": "retryBackendC",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:49.648+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 1
    },
    {
      "retryName": "retryBackendA",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:50.259+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 2
    },
    {
      "retryName": "retryBackendA",
      "type": "ERROR",
      "creationTime": "2019-03-11T17:32:50.866+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 3
    }
  ]
}
----

The endpoint `/actuator/retryevents/{retryrName}` lists the latest emitted events of a specific Retry.
For example `/actuator/retryevents/retryBackendA`:

----
{
  "retryEvents": [
    {
      "retryName": "retryBackendA",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:49.648+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 1
    },
    {
      "retryName": "retryBackendA",
      "type": "RETRY",
      "creationTime": "2019-03-11T17:32:50.259+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 2
    },
    {
      "retryName": "retryBackendA",
      "type": "ERROR",
      "creationTime": "2019-03-11T17:32:50.866+01:00[Europe/Brussels]",
      "errorMessage": "java.io.IOException: Test Message",
      "numberOfAttempts": 3
    }
  ]
}
----

===== CircuitBreaker

The emitted CircuitBreaker events are stored in a separate circular event consumer buffers. The size of a event consumer buffer can be configured per CircuitBreaker in the application.yml file (eventConsumerBufferSize).
The demo adds a custom Spring Boot Actuator endpoint which can be used to monitor the emitted events of your CircuitBreakers.
The endpoint `/actuator/circuitbreakers` lists the names of all CircuitBreaker instances.
For example:

----
{
    "circuitBreakers": [
      "backendA",
      "backendB"
    ]
}
----

The endpoint `/management/circuitbreaker-events` lists the latest 100 emitted events of all CircuitBreaker instances.

----
{
"circuitBreakerEvents":[
  {
    "circuitBreakerName": "backendA",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:39:17.117+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "SUCCESS",
    "creationTime": "2017-01-10T15:39:20.518+01:00[Europe/Berlin]",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendB",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:41:31.159+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendB",
    "type": "SUCCESS",
    "creationTime": "2017-01-10T15:41:33.526+01:00[Europe/Berlin]",
    "durationInMs": 0
  }
]
}
----

The endpoint `/management/circuitbreaker/events/{circuitBreakerName}` lists the latest emitted events of a specific CircuitBreaker.
For example `/management/circuitbreaker/events/backendA`:

----
{
"circuitBreakerEvents":[
  {
    "circuitBreakerName": "backendA",
    "type": "ERROR",
    "creationTime": "2017-01-10T15:39:17.117+01:00[Europe/Berlin]",
    "errorMessage": "org.springframework.web.client.HttpServerErrorException: 500 This is a remote exception",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "SUCCESS",
    "creationTime": "2017-01-10T15:39:20.518+01:00[Europe/Berlin]",
    "durationInMs": 0
  },
  {
    "circuitBreakerName": "backendA",
    "type": "STATE_TRANSITION",
    "creationTime": "2017-01-10T15:39:22.341+01:00[Europe/Berlin]",
    "stateTransition": "CLOSED_TO_OPEN"
  },
  {
    "circuitBreakerName": "backendA",
    "type": "NOT_PERMITTED",
    "creationTime": "2017-01-10T15:39:22.780+01:00[Europe/Berlin]"
  }
]
}
----

===== RateLimiter
WARNING: Unlike the CircuitBreaker events, RateLimiter events require explicit subscription.
Use property resilience4j.ratelimiter.limiters.{yourBackendName}.registerHealthIndicator=true

There are literally the same endpoints implemented for RateLimiter,
so for detailed documentation please refer to previous section:

List of available endpoints:

* `/ratelimiters`
* `/ratelimiter-events`
* `/ratelimiter-events/{rateLimiterName}`

Example of response:
----
{
  "rateLimiterEvents": [
    {
      "rateLimiterName": "backendA",
      "type": "SUCCESSFUL_ACQUIRE",
      "creationTime": "2017-05-05T21:29:40.463+03:00[Europe/Uzhgorod]"
    },
    {
      "rateLimiterName": "backendA",
      "type": "SUCCESSFUL_ACQUIRE",
      "creationTime": "2017-05-05T21:29:40.469+03:00[Europe/Uzhgorod]"
    },
    {
      "rateLimiterName": "backendA",
      "type": "FAILED_ACQUIRE",
      "creationTime": "2017-05-05T21:29:41.268+03:00[Europe/Uzhgorod]"
    }
  ]
}
----
