= resilience4j-feign

Resilience4j decorators for https://github.com/OpenFeign/feign[feign].
Similar to https://github.com/OpenFeign/feign/tree/master/hystrix[HystrixFeign], 
resilience4j-feign makes it easy to incorporate "resilience" patterns into the feign framework, such as 
 the CircuitBreaker or/and RateLimiter patterns. 


== Current Features
* CircuitBreaker
* RateLimiter
* Fallback
 
 
== Example of combining patterns
``` java
        CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("backendName");
        RateLimiter rateLimiter = RateLimiter.ofDefaults("backendName");
        FeignDecorators decorators = FeignDecorators.builder()
                                         .withCircuitBreaker(circuitBreaker)
                                         .withRateLimiter(rateLimiter)
                                         .build();
        MyService myService = Resilience4jFeign.builder(decorators).target(MyService.class, "http://localhost:8080/");
```
FeignDecorators are executed at the end of the feign chain, i.e. after the Retryer, ErrorDecoder and so on.


== Ordering of Decorators
The order in which decorators are applied correspond to the order in which they are declared. 
When building `FeignDecorators`, it is important to be wary of this since the order affects the resulting behavior.

For example,
``` java
        FeignDecorators decoratorsA = FeignDecorators.builder()
                                         .withCircuitBreaker(circuitBreaker)
                                         .withRateLimiter(rateLimiter)
                                         .build();
                                         
        FeignDecorators decoratorsB = FeignDecorators.builder()
                                         .withRateLimiter(rateLimiter)
                                         .withCircuitBreaker(circuitBreaker)
                                         .build();
```        

With `decoratorsA` the RateLimiter will be called before the CircuitBreaker. That means that even if the CircuitBreaker is open, the RateLimiter will still limit the rate of calls.
`decoratorsB` applies the reserve order. Meaning that once the CircuitBreaker is open, the RateLimiter will no longer be called.



== Fallback
A fallback can be defined that is called if the a http request fails. 
The fallback must implement that same interface that is declared in the "target" method. 

``` java
        public interface MyService {
            @RequestLine("GET /greeting")
            String greeting();
        }

        MyService fallback = () -> "fallback greeting";
        CircuitBreaker circuitBreaker = CircuitBreaker.ofDefaults("backendName");
        FeignDecorators decorators = FeignDecorators.builder()
                                         .withFallback(fallback)
                                         .build();
        MyService myService = Resilience4jFeign.builder(decorators).target(MyService.class, "http://localhost:8080/", fallback);
```


== License

Copyright 2018

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.